<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pais')->insert(['nombre_pais' =>'Venezuela','codigo_pais' => 'VE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Albania','codigo_pais' => 'AL'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Alemania','codigo_pais' => 'DE'   ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Andorra','codigo_pais' => 'AD'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Angola','codigo_pais' => 'AO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Anguilla','codigo_pais' => 'AI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Antigua/Barbuda','codigo_pais' => 'AG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Antillas hol.','codigo_pais' => 'AN'   ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Antartida','codigo_pais' => 'AQ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Arabia Saudm','codigo_pais' => 'SA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Argelia','codigo_pais' => 'DZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Argentina','codigo_pais' => 'AR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Armenia','codigo_pais' => 'AM'   ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Aruba','codigo_pais' => 'AW'   ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Australia','codigo_pais' => 'AU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Austria','codigo_pais' => 'AT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Azerbaiyan','codigo_pais' => 'AZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bahamas','codigo_pais' => 'BS'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bahrein','codigo_pais' => 'BH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bangladesh','codigo_pais' => 'BD'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Barbados','codigo_pais' => 'BB'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Belice','codigo_pais' => 'BZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Benin','codigo_pais' => 'BJ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bermudas','codigo_pais' => 'BM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bielorrusia','codigo_pais' => 'BY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bolivia','codigo_pais' => 'BO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bosnia-Herz.','codigo_pais' => 'BA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Botsuana','codigo_pais' => 'BW'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Brasil','codigo_pais' => 'BR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Brunei Darussal','codigo_pais' => 'BN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bulgaria','codigo_pais' => 'BG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Burkina Faso','codigo_pais' => 'BF'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Burundi','codigo_pais' => 'BI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Butan','codigo_pais' => 'BT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Bélgica','codigo_pais' => 'BE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Cabo Verde','codigo_pais' => 'CV'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Camboya','codigo_pais' => 'KH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Camerzn','codigo_pais' => 'CM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Canada','codigo_pais' => 'CA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Chad','codigo_pais' => 'TD'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Chile','codigo_pais' => 'CL'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'China','codigo_pais' => 'CN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Chipre','codigo_pais' => 'CY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Ciudad Vaticano','codigo_pais' => 'VA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Colombia','codigo_pais' => 'CO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Comoras','codigo_pais' => 'KM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Congo','codigo_pais' => 'CG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Corea del Norte','codigo_pais' => 'KP'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Corea del Sur','codigo_pais' => 'KR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Costa Rica','codigo_pais' => 'CR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Costa de Marfil','codigo_pais' => 'CI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Croacia','codigo_pais' => 'HR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Cuba','codigo_pais' => 'CU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Dinamarca','codigo_pais' => 'DK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Dominica','codigo_pais' => 'DM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'E.A.U.','codigo_pais' => 'AE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'EE.UU.','codigo_pais' => 'US'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Ecuador','codigo_pais' => 'EC'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Egipto','codigo_pais' => 'EG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'El Salvador','codigo_pais' => 'SV'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Eritrea','codigo_pais' => 'ER'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Eslovaquia','codigo_pais' => 'SK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Eslovenia','codigo_pais' => 'SI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Espaqa','codigo_pais' => 'ES'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Estonia','codigo_pais' => 'EE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Etiopma','codigo_pais' => 'ET'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Federacisn Rusa','codigo_pais' => 'RU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Fiji','codigo_pais' => 'FJ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Filipinas','codigo_pais' => 'PH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Finlandia','codigo_pais' => 'FI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Francia','codigo_pais' => 'FR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'French S.Territ','codigo_pais' => 'TF'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Gabsn','codigo_pais' => 'GA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Gambia','codigo_pais' => 'GM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Georgia','codigo_pais' => 'GE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Ghana','codigo_pais' => 'GH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Gibraltar','codigo_pais' => 'GI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Granada','codigo_pais' => 'GD'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Grecia','codigo_pais' => 'GR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Groenlandia','codigo_pais' => 'GL'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Guadalupe','codigo_pais' => 'GP'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Guam','codigo_pais' => 'GU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Guatemala','codigo_pais' => 'GT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Guayana Franc.','codigo_pais' => 'GF'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Guinea','codigo_pais' => 'GN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Guinea Ecuator.','codigo_pais' => 'GQ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Guinea-Bissau','codigo_pais' => 'GW'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Guyana','codigo_pais' => 'GY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Haitm','codigo_pais' => 'HT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Honduras','codigo_pais' => 'HN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Hong Kong','codigo_pais' => 'HK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Hungrma','codigo_pais' => 'HU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'India','codigo_pais' => 'IN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Indonesia','codigo_pais' => 'ID'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Irak','codigo_pais' => 'IQ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Irlanda','codigo_pais' => 'IE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Iran','codigo_pais' => 'IR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Is.Vmrgenes USA','codigo_pais' => 'VI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Isl.S.Sandwich','codigo_pais' => 'GS'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Isl.Turcas y C.','codigo_pais' => 'TC'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Isl.Vmrgenes GB','codigo_pais' => 'VG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'IslMenAlejEEUU','codigo_pais' => 'UM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Isla N.Mariana','codigo_pais' => 'MP'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islandia','codigo_pais' => 'IS'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Bouvet','codigo_pais' => 'BV'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Caiman','codigo_pais' => 'KY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Coco','codigo_pais' => 'CC'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Cook','codigo_pais' => 'CK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Feroi','codigo_pais' => 'FO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Maldivas','codigo_pais' => 'MV'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Malvinas','codigo_pais' => 'FK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Marshall','codigo_pais' => 'MH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Navidad','codigo_pais' => 'CX'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Niue','codigo_pais' => 'NU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Norfolk','codigo_pais' => 'NF'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Pitcairn','codigo_pais' => 'PN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Salomsn','codigo_pais' => 'SB'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Islas Tokelau','codigo_pais' => 'TK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Israel','codigo_pais' => 'IL'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Italia','codigo_pais' => 'IT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Jamaica','codigo_pais' => 'JM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Japsn','codigo_pais' => 'JP'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Jordania','codigo_pais' => 'JO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Kazajistan','codigo_pais' => 'KZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Kenia','codigo_pais' => 'KE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Kirguizistan','codigo_pais' => 'KG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Kiribati','codigo_pais' => 'KI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Kuwait','codigo_pais' => 'KW'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Laos','codigo_pais' => 'LA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Lesotho','codigo_pais' => 'LS'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Letonia','codigo_pais' => 'LV'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Liberia','codigo_pais' => 'LR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Libia','codigo_pais' => 'LY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Liechtenstein','codigo_pais' => 'LI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Lituania','codigo_pais' => 'LT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Luxemburgo','codigo_pais' => 'LU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Lmbano','codigo_pais' => 'LB'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Macau','codigo_pais' => 'MO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Macedonia','codigo_pais' => 'MK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Madagascar','codigo_pais' => 'MG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Malasia','codigo_pais' => 'MY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Malaui','codigo_pais' => 'MW'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Mali','codigo_pais' => 'ML'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Malta','codigo_pais' => 'MT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Marruecos','codigo_pais' => 'MA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Martinicas','codigo_pais' => 'MQ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Mauricio (Isl.)','codigo_pais' => 'MU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Mauritania','codigo_pais' => 'MR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Mayotte','codigo_pais' => 'YT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Micronesia','codigo_pais' => 'FM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Moldavia','codigo_pais' => 'MD'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Mongolia','codigo_pais' => 'MN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Montserrat','codigo_pais' => 'MS'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Mozambique','codigo_pais' => 'MZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Myanmar','codigo_pais' => 'MM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Mixico','codigo_pais' => 'MX'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Msnaco','codigo_pais' => 'MC'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Namibia','codigo_pais' => 'NA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Nauru','codigo_pais' => 'NR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Nepal','codigo_pais' => 'NP'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Nicaragua','codigo_pais' => 'NI'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Nigeria','codigo_pais' => 'NG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Nigeria','codigo_pais' => 'NE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Noruega','codigo_pais' => 'NO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Nueva Caledonia','codigo_pais' => 'NC'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Nueva Zelanda','codigo_pais' => 'NZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Oman','codigo_pais' => 'OM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Pakistan','codigo_pais' => 'PK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Palau','codigo_pais' => 'PW'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Panama','codigo_pais' => 'PA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'PapuaNvaGuinea','codigo_pais' => 'PG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Paraguay','codigo_pais' => 'PY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Pamses Bajos','codigo_pais' => 'NL'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Perz','codigo_pais' => 'PE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Polinesia fran.','codigo_pais' => 'PF'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Polonia','codigo_pais' => 'PL'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Portugal','codigo_pais' => 'PT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Puerto Rico','codigo_pais' => 'PR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Qatar','codigo_pais' => 'QA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Reino Unido','codigo_pais' => 'GB'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Rep.Centroafr.','codigo_pais' => 'CF'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Rep.Dominicana','codigo_pais' => 'DO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Repzblica Checa','codigo_pais' => 'CZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Repzblica Congo','codigo_pais' => 'CD'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Reunisn','codigo_pais' => 'RE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Ruanda','codigo_pais' => 'RW'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Rumanma','codigo_pais' => 'RO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'S.Tomi,Prmncipe','codigo_pais' => 'ST'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Samoa Occident.','codigo_pais' => 'WS'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Samoa americana','codigo_pais' => 'AS'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'San Marino','codigo_pais' => 'SM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'San Vicente','codigo_pais' => 'VC'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Santa Helena','codigo_pais' => 'SH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Santa Lucma','codigo_pais' => 'LC'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Senegal','codigo_pais' => 'SN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Seychelles','codigo_pais' => 'SC'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Sierra Leona','codigo_pais' => 'SL'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Singapur','codigo_pais' => 'SG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Siria','codigo_pais' => 'SY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Somalia','codigo_pais' => 'SO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Sri Lanka','codigo_pais' => 'LK'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'St.Chr.,Nevis','codigo_pais' => 'KN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'StPier.,Miquel.','codigo_pais' => 'PM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Suazilandia','codigo_pais' => 'SZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Sudafrica','codigo_pais' => 'ZA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Sudan','codigo_pais' => 'SD'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Suecia','codigo_pais' => 'SE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Suiza','codigo_pais' => 'CH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Surinam','codigo_pais' => 'SR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Svalbard','codigo_pais' => 'SJ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Sahara occid.','codigo_pais' => 'EH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Tadjikistan','codigo_pais' => 'TJ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Tailandia','codigo_pais' => 'TH'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Taiwan','codigo_pais' => 'TW'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Tanzania','codigo_pais' => 'TZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Terr.br.Oc.Ind.','codigo_pais' => 'IO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Timor oriental','codigo_pais' => 'TP'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Togo','codigo_pais' => 'TG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Tonga','codigo_pais' => 'TO'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Trinidad,Tobago','codigo_pais' => 'TT'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Turkmenistan','codigo_pais' => 'TM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Turquma','codigo_pais' => 'TR'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Tuvalz','codigo_pais' => 'TV'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Tznez','codigo_pais' => 'TN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Ucrania','codigo_pais' => 'UA'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Uganda','codigo_pais' => 'UG'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Uruguay','codigo_pais' => 'UY'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Uzbekistan','codigo_pais' => 'UZ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Vanuatu','codigo_pais' => 'VU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Afganistan','codigo_pais' => 'AF'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Vietnam','codigo_pais' => 'VN'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Wallis,Futuna','codigo_pais' => 'WF'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Yemen','codigo_pais' => 'YE'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Yibuti','codigo_pais' => 'DJ'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Yugoslavia','codigo_pais' => 'YU'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Zambia','codigo_pais' => 'ZM'  ,]);
        DB::table('pais')->insert(['nombre_pais' =>'Zimbabwe','codigo_pais' => 'ZW'  ,]);
    }
}
