<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ParroquiaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipio')->insert([ 'id_municipio'=> '1', 'nombre' => 'Alto Orinoco']);
DB::table('municipio')->insert([ 'id_municipio'=> '1', 'nombre' => 'Huachamacare Acanaña']);
DB::table('municipio')->insert([ 'id_municipio'=> '1', 'nombre' => 'Marawaka Toky Shamanaña']);
DB::table('municipio')->insert([ 'id_municipio'=> '1', 'nombre' => 'Mavaka Mavaka']);
DB::table('municipio')->insert([ 'id_municipio'=> '1', 'nombre' => 'Sierra Parima Parimabé']);
DB::table('municipio')->insert([ 'id_municipio'=> '2', 'nombre' => 'Ucata Laja Lisa']);
DB::table('municipio')->insert([ 'id_municipio'=> '2', 'nombre' => 'Yapacana Macuruco']);
DB::table('municipio')->insert([ 'id_municipio'=> '2', 'nombre' => 'Caname Guarinuma']);
DB::table('municipio')->insert([ 'id_municipio'=> '3', 'nombre' => 'Fernando Girón Tovar']);
DB::table('municipio')->insert([ 'id_municipio'=> '3', 'nombre' => 'Luis Alberto Gómez']);
DB::table('municipio')->insert([ 'id_municipio'=> '3', 'nombre' => 'Pahueña Limón de Parhueña']);
DB::table('municipio')->insert([ 'id_municipio'=> '3', 'nombre' => 'Platanillal Platanillal']);
DB::table('municipio')->insert([ 'id_municipio'=> '4', 'nombre' => 'Samariapo']);
DB::table('municipio')->insert([ 'id_municipio'=> '4', 'nombre' => 'Sipapo']);
DB::table('municipio')->insert([ 'id_municipio'=> '4', 'nombre' => 'Munduapo']);
DB::table('municipio')->insert([ 'id_municipio'=> '4', 'nombre' => 'Guayapo']);
DB::table('municipio')->insert([ 'id_municipio'=> '5', 'nombre' => 'Alto Ventuari']);
DB::table('municipio')->insert([ 'id_municipio'=> '5', 'nombre' => 'Medio Ventuari']);
DB::table('municipio')->insert([ 'id_municipio'=> '5', 'nombre' => 'Bajo Ventuari']);
DB::table('municipio')->insert([ 'id_municipio'=> '6', 'nombre' => 'Victorino']);
DB::table('municipio')->insert([ 'id_municipio'=> '6', 'nombre' => 'Comunidad']);
DB::table('municipio')->insert([ 'id_municipio'=> '7', 'nombre' => 'Casiquiare']);
DB::table('municipio')->insert([ 'id_municipio'=> '7', 'nombre' => 'Cocuy']);
DB::table('municipio')->insert([ 'id_municipio'=> '7', 'nombre' => 'San Carlos de Río Negro']);
DB::table('municipio')->insert([ 'id_municipio'=> '7', 'nombre' => 'Solano']);
DB::table('municipio')->insert([ 'id_municipio'=> '8', 'nombre' => 'Anaco']);
DB::table('municipio')->insert([ 'id_municipio'=> '8', 'nombre' => 'San Joaquín']);
DB::table('municipio')->insert([ 'id_municipio'=> '9', 'nombre' => 'Cachipo']);
DB::table('municipio')->insert([ 'id_municipio'=> '9', 'nombre' => 'Aragua de Barcelona']);
DB::table('municipio')->insert([ 'id_municipio'=> '11', 'nombre' => 'Lechería']);
DB::table('municipio')->insert([ 'id_municipio'=> '11', 'nombre' => 'El Morro']);
DB::table('municipio')->insert([ 'id_municipio'=> '12', 'nombre' => 'Puerto Píritu']);
DB::table('municipio')->insert([ 'id_municipio'=> '12', 'nombre' => 'San Miguel']);
DB::table('municipio')->insert([ 'id_municipio'=> '12', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '13', 'nombre' => 'Valle de Guanape']);
DB::table('municipio')->insert([ 'id_municipio'=> '13', 'nombre' => 'Santa Bárbara']);
DB::table('municipio')->insert([ 'id_municipio'=> '14', 'nombre' => 'El Chaparro']);
DB::table('municipio')->insert([ 'id_municipio'=> '14', 'nombre' => 'Tomás Alfaro']);
DB::table('municipio')->insert([ 'id_municipio'=> '14', 'nombre' => 'Calatrava']);
DB::table('municipio')->insert([ 'id_municipio'=> '15', 'nombre' => 'Guanta']);
DB::table('municipio')->insert([ 'id_municipio'=> '15', 'nombre' => 'Chorrerón']);
DB::table('municipio')->insert([ 'id_municipio'=> '16', 'nombre' => 'Mamo']);
DB::table('municipio')->insert([ 'id_municipio'=> '16', 'nombre' => 'Soledad']);
DB::table('municipio')->insert([ 'id_municipio'=> '17', 'nombre' => 'Mapire']);
DB::table('municipio')->insert([ 'id_municipio'=> '17', 'nombre' => 'Piar']);
DB::table('municipio')->insert([ 'id_municipio'=> '17', 'nombre' => 'Santa Clara']);
DB::table('municipio')->insert([ 'id_municipio'=> '17', 'nombre' => 'San Diego de Cabrutica']);
DB::table('municipio')->insert([ 'id_municipio'=> '17', 'nombre' => 'Uverito']);
DB::table('municipio')->insert([ 'id_municipio'=> '17', 'nombre' => 'Zuata']);
DB::table('municipio')->insert([ 'id_municipio'=> '18', 'nombre' => 'Puerto La Cruz']);
DB::table('municipio')->insert([ 'id_municipio'=> '18', 'nombre' => 'Pozuelos']);
DB::table('municipio')->insert([ 'id_municipio'=> '19', 'nombre' => 'Onoto']);
DB::table('municipio')->insert([ 'id_municipio'=> '19', 'nombre' => 'San Pablo']);
DB::table('municipio')->insert([ 'id_municipio'=> '20', 'nombre' => 'San Mateo']);
DB::table('municipio')->insert([ 'id_municipio'=> '20', 'nombre' => 'El Carito']);
DB::table('municipio')->insert([ 'id_municipio'=> '20', 'nombre' => 'Santa Inés']);
DB::table('municipio')->insert([ 'id_municipio'=> '20', 'nombre' => 'La Romereña']);
DB::table('municipio')->insert([ 'id_municipio'=> '21', 'nombre' => 'Atapirire']);
DB::table('municipio')->insert([ 'id_municipio'=> '21', 'nombre' => 'Boca del Pao']);
DB::table('municipio')->insert([ 'id_municipio'=> '21', 'nombre' => 'El Pao']);
DB::table('municipio')->insert([ 'id_municipio'=> '21', 'nombre' => 'Pariaguán']);
DB::table('municipio')->insert([ 'id_municipio'=> '22', 'nombre' => 'Cantaura']);
DB::table('municipio')->insert([ 'id_municipio'=> '22', 'nombre' => 'Libertador']);
DB::table('municipio')->insert([ 'id_municipio'=> '22', 'nombre' => 'Santa Rosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '22', 'nombre' => 'Urica']);
DB::table('municipio')->insert([ 'id_municipio'=> '23', 'nombre' => 'Píritu']);
DB::table('municipio')->insert([ 'id_municipio'=> '23', 'nombre' => 'San Francisco']);
DB::table('municipio')->insert([ 'id_municipio'=> '24', 'nombre' => 'San José de Guanipa']);
DB::table('municipio')->insert([ 'id_municipio'=> '25', 'nombre' => 'Boca de Uchire']);
DB::table('municipio')->insert([ 'id_municipio'=> '25', 'nombre' => 'Boca de Chávez']);
DB::table('municipio')->insert([ 'id_municipio'=> '26', 'nombre' => 'Pueblo Nuevo']);
DB::table('municipio')->insert([ 'id_municipio'=> '26', 'nombre' => 'Santa Ana']);
DB::table('municipio')->insert([ 'id_municipio'=> '27', 'nombre' => 'Bergantín']);
DB::table('municipio')->insert([ 'id_municipio'=> '27', 'nombre' => 'Caigua']);
DB::table('municipio')->insert([ 'id_municipio'=> '27', 'nombre' => 'El Carmen']);
DB::table('municipio')->insert([ 'id_municipio'=> '27', 'nombre' => 'El Pilar']);
DB::table('municipio')->insert([ 'id_municipio'=> '27', 'nombre' => 'Naricual']);
DB::table('municipio')->insert([ 'id_municipio'=> '27', 'nombre' => 'San Crsitóbal']);
DB::table('municipio')->insert([ 'id_municipio'=> '28', 'nombre' => 'Edmundo Barrios']);
DB::table('municipio')->insert([ 'id_municipio'=> '28', 'nombre' => 'Miguel Otero Silva']);
DB::table('municipio')->insert([ 'id_municipio'=> '29', 'nombre' => 'Achaguas']);
DB::table('municipio')->insert([ 'id_municipio'=> '29', 'nombre' => 'Apurito']);
DB::table('municipio')->insert([ 'id_municipio'=> '29', 'nombre' => 'El Yagual']);
DB::table('municipio')->insert([ 'id_municipio'=> '29', 'nombre' => 'Guachara']);
DB::table('municipio')->insert([ 'id_municipio'=> '29', 'nombre' => 'Mucuritas']);
DB::table('municipio')->insert([ 'id_municipio'=> '29', 'nombre' => 'Queseras del medio']);
DB::table('municipio')->insert([ 'id_municipio'=> '30', 'nombre' => 'Biruaca']);
DB::table('municipio')->insert([ 'id_municipio'=> '31', 'nombre' => 'Bruzual']);
DB::table('municipio')->insert([ 'id_municipio'=> '31', 'nombre' => 'Mantecal']);
DB::table('municipio')->insert([ 'id_municipio'=> '31', 'nombre' => 'Quintero']);
DB::table('municipio')->insert([ 'id_municipio'=> '31', 'nombre' => 'Rincón Hondo']);
DB::table('municipio')->insert([ 'id_municipio'=> '31', 'nombre' => 'San Vicente']);
DB::table('municipio')->insert([ 'id_municipio'=> '32', 'nombre' => 'Guasdualito']);
DB::table('municipio')->insert([ 'id_municipio'=> '32', 'nombre' => 'Aramendi']);
DB::table('municipio')->insert([ 'id_municipio'=> '32', 'nombre' => 'El Amparo']);
DB::table('municipio')->insert([ 'id_municipio'=> '32', 'nombre' => 'San Camilo']);
DB::table('municipio')->insert([ 'id_municipio'=> '32', 'nombre' => 'Urdaneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '33', 'nombre' => 'San Juan de Payara']);
DB::table('municipio')->insert([ 'id_municipio'=> '33', 'nombre' => 'Codazzi']);
DB::table('municipio')->insert([ 'id_municipio'=> '33', 'nombre' => 'Cunaviche']);
DB::table('municipio')->insert([ 'id_municipio'=> '34', 'nombre' => 'Elorza']);
DB::table('municipio')->insert([ 'id_municipio'=> '34', 'nombre' => 'La Trinidad']);
DB::table('municipio')->insert([ 'id_municipio'=> '35', 'nombre' => 'San Fernando']);
DB::table('municipio')->insert([ 'id_municipio'=> '35', 'nombre' => 'El Recreo']);
DB::table('municipio')->insert([ 'id_municipio'=> '35', 'nombre' => 'Peñalver']);
DB::table('municipio')->insert([ 'id_municipio'=> '35', 'nombre' => 'San Rafael de Atamaica']);
DB::table('municipio')->insert([ 'id_municipio'=> '36', 'nombre' => 'Pedro José Ovalles']);
DB::table('municipio')->insert([ 'id_municipio'=> '36', 'nombre' => 'Joaquín Crespo']);
DB::table('municipio')->insert([ 'id_municipio'=> '36', 'nombre' => 'José Casanova Godoy']);
DB::table('municipio')->insert([ 'id_municipio'=> '36', 'nombre' => 'Madre María de San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '36', 'nombre' => 'Andrés Eloy Blanco']);
DB::table('municipio')->insert([ 'id_municipio'=> '36', 'nombre' => 'Los Tacarigua']);
DB::table('municipio')->insert([ 'id_municipio'=> '36', 'nombre' => 'Las Delicias']);
DB::table('municipio')->insert([ 'id_municipio'=> '36', 'nombre' => 'Choroní']);
DB::table('municipio')->insert([ 'id_municipio'=> '37', 'nombre' => 'Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '38', 'nombre' => 'Camatagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '38', 'nombre' => 'Carmen de Cura']);
DB::table('municipio')->insert([ 'id_municipio'=> '39', 'nombre' => 'Santa Rita']);
DB::table('municipio')->insert([ 'id_municipio'=> '39', 'nombre' => 'Francisco de Miranda']);
DB::table('municipio')->insert([ 'id_municipio'=> '39', 'nombre' => 'Moseñor Feliciano González']);
DB::table('municipio')->insert([ 'id_municipio'=> '40', 'nombre' => 'Santa Cruz']);
DB::table('municipio')->insert([ 'id_municipio'=> '41', 'nombre' => 'José Félix Ribas']);
DB::table('municipio')->insert([ 'id_municipio'=> '41', 'nombre' => 'Castor Nieves Ríos']);
DB::table('municipio')->insert([ 'id_municipio'=> '41', 'nombre' => 'Las Guacamayas']);
DB::table('municipio')->insert([ 'id_municipio'=> '41', 'nombre' => 'Pao de Zárate']);
DB::table('municipio')->insert([ 'id_municipio'=> '41', 'nombre' => 'Zuata']);
DB::table('municipio')->insert([ 'id_municipio'=> '42', 'nombre' => 'José Rafael Revenga']);
DB::table('municipio')->insert([ 'id_municipio'=> '43', 'nombre' => 'Palo Negro']);
DB::table('municipio')->insert([ 'id_municipio'=> '43', 'nombre' => 'San Martín de Porres']);
DB::table('municipio')->insert([ 'id_municipio'=> '44', 'nombre' => 'El Limón']);
DB::table('municipio')->insert([ 'id_municipio'=> '44', 'nombre' => 'Caña de Azúcar']);
DB::table('municipio')->insert([ 'id_municipio'=> '45', 'nombre' => 'Ocumare de la Costa']);
DB::table('municipio')->insert([ 'id_municipio'=> '46', 'nombre' => 'San Casimiro']);
DB::table('municipio')->insert([ 'id_municipio'=> '46', 'nombre' => 'Güiripa']);
DB::table('municipio')->insert([ 'id_municipio'=> '46', 'nombre' => 'Ollas de Caramacate']);
DB::table('municipio')->insert([ 'id_municipio'=> '46', 'nombre' => 'Valle Morín']);
DB::table('municipio')->insert([ 'id_municipio'=> '47', 'nombre' => 'San Sebastían']);
DB::table('municipio')->insert([ 'id_municipio'=> '48', 'nombre' => 'Turmero']);
DB::table('municipio')->insert([ 'id_municipio'=> '48', 'nombre' => 'Arevalo Aponte']);
DB::table('municipio')->insert([ 'id_municipio'=> '48', 'nombre' => 'Chuao']);
DB::table('municipio')->insert([ 'id_municipio'=> '48', 'nombre' => 'Samán de Güere']);
DB::table('municipio')->insert([ 'id_municipio'=> '48', 'nombre' => 'Alfredo Pacheco Miranda']);
DB::table('municipio')->insert([ 'id_municipio'=> '49', 'nombre' => 'Santos Michelena']);
DB::table('municipio')->insert([ 'id_municipio'=> '49', 'nombre' => 'Tiara']);
DB::table('municipio')->insert([ 'id_municipio'=> '50', 'nombre' => 'Cagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '50', 'nombre' => 'Bella Vista']);
DB::table('municipio')->insert([ 'id_municipio'=> '51', 'nombre' => 'Tovar']);
DB::table('municipio')->insert([ 'id_municipio'=> '52', 'nombre' => 'Urdaneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '52', 'nombre' => 'Las Peñitas']);
DB::table('municipio')->insert([ 'id_municipio'=> '52', 'nombre' => 'San Francisco de Cara']);
DB::table('municipio')->insert([ 'id_municipio'=> '52', 'nombre' => 'Taguay']);
DB::table('municipio')->insert([ 'id_municipio'=> '53', 'nombre' => 'Zamora']);
DB::table('municipio')->insert([ 'id_municipio'=> '53', 'nombre' => 'Magdaleno']);
DB::table('municipio')->insert([ 'id_municipio'=> '53', 'nombre' => 'San Francisco de Asís']);
DB::table('municipio')->insert([ 'id_municipio'=> '53', 'nombre' => 'Valles de Tucutunemo']);
DB::table('municipio')->insert([ 'id_municipio'=> '53', 'nombre' => 'Augusto Mijares']);
DB::table('municipio')->insert([ 'id_municipio'=> '54', 'nombre' => 'Sabaneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '54', 'nombre' => 'Juan Antonio Rodríguez Domínguez']);
DB::table('municipio')->insert([ 'id_municipio'=> '55', 'nombre' => 'El Cantón']);
DB::table('municipio')->insert([ 'id_municipio'=> '55', 'nombre' => 'Santa Cruz de Guacas']);
DB::table('municipio')->insert([ 'id_municipio'=> '55', 'nombre' => 'Puerto Vivas']);
DB::table('municipio')->insert([ 'id_municipio'=> '56', 'nombre' => 'Ticoporo']);
DB::table('municipio')->insert([ 'id_municipio'=> '56', 'nombre' => 'Nicolás Pulido']);
DB::table('municipio')->insert([ 'id_municipio'=> '56', 'nombre' => 'Andrés Bello']);
DB::table('municipio')->insert([ 'id_municipio'=> '57', 'nombre' => 'Arismendi']);
DB::table('municipio')->insert([ 'id_municipio'=> '57', 'nombre' => 'Guadarrama']);
DB::table('municipio')->insert([ 'id_municipio'=> '57', 'nombre' => 'La Unión']);
DB::table('municipio')->insert([ 'id_municipio'=> '57', 'nombre' => 'San Antonio']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Barinas']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Alberto Arvelo Larriva']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'San Silvestre']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Santa Inés']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Santa Lucía']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Torumos']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'El Carmen']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Rómulo Betancourt']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Corazón de Jesús']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Ramón Ignacio Méndez']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Alto Barinas']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Manuel Palacio Fajardo']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Juan Antonio Rodríguez Domínguez']);
DB::table('municipio')->insert([ 'id_municipio'=> '58', 'nombre' => 'Dominga Ortiz de Páez']);
DB::table('municipio')->insert([ 'id_municipio'=> '59', 'nombre' => 'Barinitas']);
DB::table('municipio')->insert([ 'id_municipio'=> '59', 'nombre' => 'Altamira de Cáceres']);
DB::table('municipio')->insert([ 'id_municipio'=> '59', 'nombre' => 'Calderas']);
DB::table('municipio')->insert([ 'id_municipio'=> '60', 'nombre' => 'Barrancas']);
DB::table('municipio')->insert([ 'id_municipio'=> '60', 'nombre' => 'El Socorro']);
DB::table('municipio')->insert([ 'id_municipio'=> '60', 'nombre' => 'Mazparrito']);
DB::table('municipio')->insert([ 'id_municipio'=> '61', 'nombre' => 'Santa Bárbara']);
DB::table('municipio')->insert([ 'id_municipio'=> '61', 'nombre' => 'Pedro Briceño Méndez']);
DB::table('municipio')->insert([ 'id_municipio'=> '61', 'nombre' => 'Ramón Ignacio Méndez']);
DB::table('municipio')->insert([ 'id_municipio'=> '61', 'nombre' => 'José Ignacio del Pumar']);
DB::table('municipio')->insert([ 'id_municipio'=> '62', 'nombre' => 'Obispos']);
DB::table('municipio')->insert([ 'id_municipio'=> '62', 'nombre' => 'Guasimitos']);
DB::table('municipio')->insert([ 'id_municipio'=> '62', 'nombre' => 'El Real']);
DB::table('municipio')->insert([ 'id_municipio'=> '62', 'nombre' => 'La Luz']);
DB::table('municipio')->insert([ 'id_municipio'=> '63', 'nombre' => 'Ciudad Bolívia']);
DB::table('municipio')->insert([ 'id_municipio'=> '63', 'nombre' => 'José Ignacio Briceño']);
DB::table('municipio')->insert([ 'id_municipio'=> '63', 'nombre' => 'José Félix Ribas']);
DB::table('municipio')->insert([ 'id_municipio'=> '63', 'nombre' => 'Páez']);
DB::table('municipio')->insert([ 'id_municipio'=> '64', 'nombre' => 'Libertad']);
DB::table('municipio')->insert([ 'id_municipio'=> '64', 'nombre' => 'Dolores']);
DB::table('municipio')->insert([ 'id_municipio'=> '64', 'nombre' => 'Santa Rosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '64', 'nombre' => 'Palacio Fajardo']);
DB::table('municipio')->insert([ 'id_municipio'=> '65', 'nombre' => 'Ciudad de Nutrias']);
DB::table('municipio')->insert([ 'id_municipio'=> '65', 'nombre' => 'El Regalo']);
DB::table('municipio')->insert([ 'id_municipio'=> '65', 'nombre' => 'Puerto Nutrias']);
DB::table('municipio')->insert([ 'id_municipio'=> '65', 'nombre' => 'Santa Catalina']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Cachamay']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Chirica']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Dalla Costa']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Once de Abril']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Simón Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Unare']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Universidad']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Vista al Sol']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Pozo Verde']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => 'Yocoima']);
DB::table('municipio')->insert([ 'id_municipio'=> '66', 'nombre' => '5 de Julio']);
DB::table('municipio')->insert([ 'id_municipio'=> '67', 'nombre' => 'Cedeño']);
DB::table('municipio')->insert([ 'id_municipio'=> '67', 'nombre' => 'Altagracia']);
DB::table('municipio')->insert([ 'id_municipio'=> '67', 'nombre' => 'Ascensión Farreras']);
DB::table('municipio')->insert([ 'id_municipio'=> '67', 'nombre' => 'Guaniamo']);
DB::table('municipio')->insert([ 'id_municipio'=> '67', 'nombre' => 'La Urbana']);
DB::table('municipio')->insert([ 'id_municipio'=> '67', 'nombre' => 'Pijiguaos']);
DB::table('municipio')->insert([ 'id_municipio'=> '68', 'nombre' => 'El Callao']);
DB::table('municipio')->insert([ 'id_municipio'=> '69', 'nombre' => 'Gran Sabana']);
DB::table('municipio')->insert([ 'id_municipio'=> '69', 'nombre' => 'Ikabarú']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'Catedral']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'Zea']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'Orinoco']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'José Antonio Páez']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'Marhuanta']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'Agua Salada']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'Vista Hermosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'La Sabanita']);
DB::table('municipio')->insert([ 'id_municipio'=> '70', 'nombre' => 'Panapana']);
DB::table('municipio')->insert([ 'id_municipio'=> '71', 'nombre' => 'Andrés Eloy Blanco']);
DB::table('municipio')->insert([ 'id_municipio'=> '71', 'nombre' => 'Pedro Cova']);
DB::table('municipio')->insert([ 'id_municipio'=> '72', 'nombre' => 'Raúl Leoni']);
DB::table('municipio')->insert([ 'id_municipio'=> '72', 'nombre' => 'Barceloneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '72', 'nombre' => 'Santa Bárbara']);
DB::table('municipio')->insert([ 'id_municipio'=> '72', 'nombre' => 'San Francisco']);
DB::table('municipio')->insert([ 'id_municipio'=> '73', 'nombre' => 'Roscio']);
DB::table('municipio')->insert([ 'id_municipio'=> '73', 'nombre' => 'Salóm']);
DB::table('municipio')->insert([ 'id_municipio'=> '74', 'nombre' => 'Sifontes']);
DB::table('municipio')->insert([ 'id_municipio'=> '74', 'nombre' => 'Dalla Costa']);
DB::table('municipio')->insert([ 'id_municipio'=> '74', 'nombre' => 'San Isidro']);
DB::table('municipio')->insert([ 'id_municipio'=> '75', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '75', 'nombre' => 'Aripao']);
DB::table('municipio')->insert([ 'id_municipio'=> '75', 'nombre' => 'Guarataro']);
DB::table('municipio')->insert([ 'id_municipio'=> '75', 'nombre' => 'Las Majadas']);
DB::table('municipio')->insert([ 'id_municipio'=> '75', 'nombre' => 'Moitaco']);
DB::table('municipio')->insert([ 'id_municipio'=> '76', 'nombre' => 'Padre Pedro Chien']);
DB::table('municipio')->insert([ 'id_municipio'=> '76', 'nombre' => 'Río Grande']);
DB::table('municipio')->insert([ 'id_municipio'=> '77', 'nombre' => 'Bejuma']);
DB::table('municipio')->insert([ 'id_municipio'=> '77', 'nombre' => 'Canoabo']);
DB::table('municipio')->insert([ 'id_municipio'=> '77', 'nombre' => 'Simón Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '78', 'nombre' => 'Güigüe']);
DB::table('municipio')->insert([ 'id_municipio'=> '78', 'nombre' => 'Carabobo']);
DB::table('municipio')->insert([ 'id_municipio'=> '78', 'nombre' => 'Tacarigua']);
DB::table('municipio')->insert([ 'id_municipio'=> '79', 'nombre' => 'Mariara']);
DB::table('municipio')->insert([ 'id_municipio'=> '79', 'nombre' => 'Aguas Calientes']);
DB::table('municipio')->insert([ 'id_municipio'=> '80', 'nombre' => 'Ciudad Alianza']);
DB::table('municipio')->insert([ 'id_municipio'=> '80', 'nombre' => 'Guacara']);
DB::table('municipio')->insert([ 'id_municipio'=> '80', 'nombre' => 'Yagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '81', 'nombre' => 'Morón']);
DB::table('municipio')->insert([ 'id_municipio'=> '81', 'nombre' => 'Yagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '82', 'nombre' => 'Tocuyito']);
DB::table('municipio')->insert([ 'id_municipio'=> '82', 'nombre' => 'Independencia']);
DB::table('municipio')->insert([ 'id_municipio'=> '83', 'nombre' => 'Los Guayos']);
DB::table('municipio')->insert([ 'id_municipio'=> '84', 'nombre' => 'Miranda']);
DB::table('municipio')->insert([ 'id_municipio'=> '85', 'nombre' => 'Montalbán']);
DB::table('municipio')->insert([ 'id_municipio'=> '86', 'nombre' => 'Naguanagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '87', 'nombre' => 'Bartolomé Salóm']);
DB::table('municipio')->insert([ 'id_municipio'=> '87', 'nombre' => 'Democracia']);
DB::table('municipio')->insert([ 'id_municipio'=> '87', 'nombre' => 'Fraternidad']);
DB::table('municipio')->insert([ 'id_municipio'=> '87', 'nombre' => 'Goaigoaza']);
DB::table('municipio')->insert([ 'id_municipio'=> '87', 'nombre' => 'Juan José Flores']);
DB::table('municipio')->insert([ 'id_municipio'=> '87', 'nombre' => 'Unión']);
DB::table('municipio')->insert([ 'id_municipio'=> '87', 'nombre' => 'Borburata']);
DB::table('municipio')->insert([ 'id_municipio'=> '87', 'nombre' => 'Patanemo']);
DB::table('municipio')->insert([ 'id_municipio'=> '88', 'nombre' => 'San Diego']);
DB::table('municipio')->insert([ 'id_municipio'=> '89', 'nombre' => 'San Joaquín']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'Candelaria']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'Catedral']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'El Socorro']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'Miguel Peña']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'Rafael Urdaneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'San Blas']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'Santa Rosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '90', 'nombre' => 'Negro Primero']);
DB::table('municipio')->insert([ 'id_municipio'=> '91', 'nombre' => 'Cojedes']);
DB::table('municipio')->insert([ 'id_municipio'=> '91', 'nombre' => 'Juan de Mata Suárez']);
DB::table('municipio')->insert([ 'id_municipio'=> '92', 'nombre' => 'Tinaquillo']);
DB::table('municipio')->insert([ 'id_municipio'=> '93', 'nombre' => 'El Baúl']);
DB::table('municipio')->insert([ 'id_municipio'=> '93', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '94', 'nombre' => 'La Aguadita']);
DB::table('municipio')->insert([ 'id_municipio'=> '94', 'nombre' => 'Macapo']);
DB::table('municipio')->insert([ 'id_municipio'=> '95', 'nombre' => 'El Pao']);
DB::table('municipio')->insert([ 'id_municipio'=> '96', 'nombre' => 'El Amparo']);
DB::table('municipio')->insert([ 'id_municipio'=> '96', 'nombre' => 'Libertad de Cojedes']);
DB::table('municipio')->insert([ 'id_municipio'=> '97', 'nombre' => 'Rómulo Gallegos']);
DB::table('municipio')->insert([ 'id_municipio'=> '98', 'nombre' => 'San Carlos de Austria']);
DB::table('municipio')->insert([ 'id_municipio'=> '98', 'nombre' => 'Juan Ángel Bravo']);
DB::table('municipio')->insert([ 'id_municipio'=> '98', 'nombre' => 'Manuel Manrique']);
DB::table('municipio')->insert([ 'id_municipio'=> '99', 'nombre' => 'General en Jefe José Laurencio Silva']);
DB::table('municipio')->insert([ 'id_municipio'=> '100', 'nombre' => 'Curiapo']);
DB::table('municipio')->insert([ 'id_municipio'=> '100', 'nombre' => 'Almirante Luis Brión']);
DB::table('municipio')->insert([ 'id_municipio'=> '100', 'nombre' => 'Francisco Aniceto Lugo']);
DB::table('municipio')->insert([ 'id_municipio'=> '100', 'nombre' => 'Manuel Renaud']);
DB::table('municipio')->insert([ 'id_municipio'=> '100', 'nombre' => 'Padre Barral']);
DB::table('municipio')->insert([ 'id_municipio'=> '100', 'nombre' => 'Santos de Abelgas']);
DB::table('municipio')->insert([ 'id_municipio'=> '101', 'nombre' => 'Imataca']);
DB::table('municipio')->insert([ 'id_municipio'=> '101', 'nombre' => 'Cinco de Julio']);
DB::table('municipio')->insert([ 'id_municipio'=> '101', 'nombre' => 'Juan Bautista Arismendi']);
DB::table('municipio')->insert([ 'id_municipio'=> '101', 'nombre' => 'Manuel Piar']);
DB::table('municipio')->insert([ 'id_municipio'=> '101', 'nombre' => 'Rómulo Gallegos']);
DB::table('municipio')->insert([ 'id_municipio'=> '102', 'nombre' => 'Pedernales']);
DB::table('municipio')->insert([ 'id_municipio'=> '102', 'nombre' => 'Luis Beltrán Prieto Figueroa']);
DB::table('municipio')->insert([ 'id_municipio'=> '103', 'nombre' => 'San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '103', 'nombre' => 'José Vidal Marcano']);
DB::table('municipio')->insert([ 'id_municipio'=> '103', 'nombre' => 'Juan Millán']);
DB::table('municipio')->insert([ 'id_municipio'=> '103', 'nombre' => 'Leonardo Ruíz Pineda']);
DB::table('municipio')->insert([ 'id_municipio'=> '103', 'nombre' => 'Mariscal Antonio José de Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '103', 'nombre' => 'Monseñor Argimiro García']);
DB::table('municipio')->insert([ 'id_municipio'=> '103', 'nombre' => 'San Rafael']);
DB::table('municipio')->insert([ 'id_municipio'=> '103', 'nombre' => 'Virgen del Valle']);
DB::table('municipio')->insert([ 'id_municipio'=> '10', 'nombre' => 'Clarines']);
DB::table('municipio')->insert([ 'id_municipio'=> '10', 'nombre' => 'Guanape']);
DB::table('municipio')->insert([ 'id_municipio'=> '10', 'nombre' => 'Sabana de Uchire']);
DB::table('municipio')->insert([ 'id_municipio'=> '104', 'nombre' => 'Capadare']);
DB::table('municipio')->insert([ 'id_municipio'=> '104', 'nombre' => 'La Pastora']);
DB::table('municipio')->insert([ 'id_municipio'=> '104', 'nombre' => 'Libertador']);
DB::table('municipio')->insert([ 'id_municipio'=> '104', 'nombre' => 'San Juan de los Cayos']);
DB::table('municipio')->insert([ 'id_municipio'=> '105', 'nombre' => 'Aracua']);
DB::table('municipio')->insert([ 'id_municipio'=> '105', 'nombre' => 'La Peña']);
DB::table('municipio')->insert([ 'id_municipio'=> '105', 'nombre' => 'San Luis']);
DB::table('municipio')->insert([ 'id_municipio'=> '106', 'nombre' => 'Bariro']);
DB::table('municipio')->insert([ 'id_municipio'=> '106', 'nombre' => 'Borojó']);
DB::table('municipio')->insert([ 'id_municipio'=> '106', 'nombre' => 'Capatárida']);
DB::table('municipio')->insert([ 'id_municipio'=> '106', 'nombre' => 'Guajiro']);
DB::table('municipio')->insert([ 'id_municipio'=> '106', 'nombre' => 'Seque']);
DB::table('municipio')->insert([ 'id_municipio'=> '106', 'nombre' => 'Zazárida']);
DB::table('municipio')->insert([ 'id_municipio'=> '106', 'nombre' => 'Valle de Eroa']);
DB::table('municipio')->insert([ 'id_municipio'=> '107', 'nombre' => 'Cacique Manaure']);
DB::table('municipio')->insert([ 'id_municipio'=> '108', 'nombre' => 'Norte']);
DB::table('municipio')->insert([ 'id_municipio'=> '108', 'nombre' => 'Carirubana']);
DB::table('municipio')->insert([ 'id_municipio'=> '108', 'nombre' => 'Santa Ana']);
DB::table('municipio')->insert([ 'id_municipio'=> '108', 'nombre' => 'Urbana Punta Cardón']);
DB::table('municipio')->insert([ 'id_municipio'=> '109', 'nombre' => 'La Vela de Coro']);
DB::table('municipio')->insert([ 'id_municipio'=> '109', 'nombre' => 'Acurigua']);
DB::table('municipio')->insert([ 'id_municipio'=> '109', 'nombre' => 'Guaibacoa']);
DB::table('municipio')->insert([ 'id_municipio'=> '109', 'nombre' => 'Las Calderas']);
DB::table('municipio')->insert([ 'id_municipio'=> '109', 'nombre' => 'Macoruca']);
DB::table('municipio')->insert([ 'id_municipio'=> '110', 'nombre' => 'Dabajuro']);
DB::table('municipio')->insert([ 'id_municipio'=> '111', 'nombre' => 'Agua Clara']);
DB::table('municipio')->insert([ 'id_municipio'=> '111', 'nombre' => 'Avaria']);
DB::table('municipio')->insert([ 'id_municipio'=> '111', 'nombre' => 'Pedregal']);
DB::table('municipio')->insert([ 'id_municipio'=> '111', 'nombre' => 'Piedra Grande']);
DB::table('municipio')->insert([ 'id_municipio'=> '111', 'nombre' => 'Purureche']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'Adaure']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'Adícora']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'Baraived']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'Buena Vista']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'Jadacaquiva']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'El Vínculo']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'El Hato']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'Moruy']);
DB::table('municipio')->insert([ 'id_municipio'=> '112', 'nombre' => 'Pueblo Nuevo']);
DB::table('municipio')->insert([ 'id_municipio'=> '113', 'nombre' => 'Agua Larga']);
DB::table('municipio')->insert([ 'id_municipio'=> '113', 'nombre' => 'El Paují']);
DB::table('municipio')->insert([ 'id_municipio'=> '113', 'nombre' => 'Independencia']);
DB::table('municipio')->insert([ 'id_municipio'=> '113', 'nombre' => 'Mapararí']);
DB::table('municipio')->insert([ 'id_municipio'=> '114', 'nombre' => 'Agua Linda']);
DB::table('municipio')->insert([ 'id_municipio'=> '114', 'nombre' => 'Araurima']);
DB::table('municipio')->insert([ 'id_municipio'=> '114', 'nombre' => 'Jacura']);
DB::table('municipio')->insert([ 'id_municipio'=> '115', 'nombre' => 'Tucacas']);
DB::table('municipio')->insert([ 'id_municipio'=> '115', 'nombre' => 'Boca de Aroa']);
DB::table('municipio')->insert([ 'id_municipio'=> '116', 'nombre' => 'Los Taques']);
DB::table('municipio')->insert([ 'id_municipio'=> '116', 'nombre' => 'Judibana']);
DB::table('municipio')->insert([ 'id_municipio'=> '117', 'nombre' => 'Mene de Mauroa']);
DB::table('municipio')->insert([ 'id_municipio'=> '117', 'nombre' => 'San Félix']);
DB::table('municipio')->insert([ 'id_municipio'=> '117', 'nombre' => 'Casigua']);
DB::table('municipio')->insert([ 'id_municipio'=> '118', 'nombre' => 'Guzmán Guillermo']);
DB::table('municipio')->insert([ 'id_municipio'=> '118', 'nombre' => 'Mitare']);
DB::table('municipio')->insert([ 'id_municipio'=> '118', 'nombre' => 'Río Seco']);
DB::table('municipio')->insert([ 'id_municipio'=> '118', 'nombre' => 'Sabaneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '118', 'nombre' => 'San Antonio']);
DB::table('municipio')->insert([ 'id_municipio'=> '118', 'nombre' => 'San Gabriel']);
DB::table('municipio')->insert([ 'id_municipio'=> '118', 'nombre' => 'Santa Ana']);
DB::table('municipio')->insert([ 'id_municipio'=> '119', 'nombre' => 'Boca del Tocuyo']);
DB::table('municipio')->insert([ 'id_municipio'=> '119', 'nombre' => 'Chichiriviche']);
DB::table('municipio')->insert([ 'id_municipio'=> '119', 'nombre' => 'Tocuyo de la Costa']);
DB::table('municipio')->insert([ 'id_municipio'=> '120', 'nombre' => 'Palmasola']);
DB::table('municipio')->insert([ 'id_municipio'=> '121', 'nombre' => 'Cabure']);
DB::table('municipio')->insert([ 'id_municipio'=> '121', 'nombre' => 'Colina']);
DB::table('municipio')->insert([ 'id_municipio'=> '121', 'nombre' => 'Curimagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '122', 'nombre' => 'San José de la Costa']);
DB::table('municipio')->insert([ 'id_municipio'=> '122', 'nombre' => 'Píritu']);
DB::table('municipio')->insert([ 'id_municipio'=> '123', 'nombre' => 'San Francisco']);
DB::table('municipio')->insert([ 'id_municipio'=> '124', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '124', 'nombre' => 'Pecaya']);
DB::table('municipio')->insert([ 'id_municipio'=> '125', 'nombre' => 'Tocópero']);
DB::table('municipio')->insert([ 'id_municipio'=> '126', 'nombre' => 'El Charal']);
DB::table('municipio')->insert([ 'id_municipio'=> '126', 'nombre' => 'Las Vegas del Tuy']);
DB::table('municipio')->insert([ 'id_municipio'=> '126', 'nombre' => 'Santa Cruz de Bucaral']);
DB::table('municipio')->insert([ 'id_municipio'=> '127', 'nombre' => 'Bruzual']);
DB::table('municipio')->insert([ 'id_municipio'=> '127', 'nombre' => 'Urumaco']);
DB::table('municipio')->insert([ 'id_municipio'=> '128', 'nombre' => 'Puerto Cumarebo']);
DB::table('municipio')->insert([ 'id_municipio'=> '128', 'nombre' => 'La Ciénaga']);
DB::table('municipio')->insert([ 'id_municipio'=> '128', 'nombre' => 'La Soledad']);
DB::table('municipio')->insert([ 'id_municipio'=> '128', 'nombre' => 'Pueblo Cumarebo']);
DB::table('municipio')->insert([ 'id_municipio'=> '128', 'nombre' => 'Zazárida']);
DB::table('municipio')->insert([ 'id_municipio'=> '113', 'nombre' => 'Churuguara']);
DB::table('municipio')->insert([ 'id_municipio'=> '129', 'nombre' => 'Camaguán']);
DB::table('municipio')->insert([ 'id_municipio'=> '129', 'nombre' => 'Puerto Miranda']);
DB::table('municipio')->insert([ 'id_municipio'=> '129', 'nombre' => 'Uverito']);
DB::table('municipio')->insert([ 'id_municipio'=> '130', 'nombre' => 'Chaguaramas']);
DB::table('municipio')->insert([ 'id_municipio'=> '131', 'nombre' => 'El Socorro']);
DB::table('municipio')->insert([ 'id_municipio'=> '132', 'nombre' => 'Tucupido']);
DB::table('municipio')->insert([ 'id_municipio'=> '132', 'nombre' => 'San Rafael de Laya']);
DB::table('municipio')->insert([ 'id_municipio'=> '133', 'nombre' => 'Altagracia de Orituco']);
DB::table('municipio')->insert([ 'id_municipio'=> '133', 'nombre' => 'San Rafael de Orituco']);
DB::table('municipio')->insert([ 'id_municipio'=> '133', 'nombre' => 'San Francisco Javier de Lezama']);
DB::table('municipio')->insert([ 'id_municipio'=> '133', 'nombre' => 'Paso Real de Macaira']);
DB::table('municipio')->insert([ 'id_municipio'=> '133', 'nombre' => 'Carlos Soublette']);
DB::table('municipio')->insert([ 'id_municipio'=> '133', 'nombre' => 'San Francisco de Macaira']);
DB::table('municipio')->insert([ 'id_municipio'=> '133', 'nombre' => 'Libertad de Orituco']);
DB::table('municipio')->insert([ 'id_municipio'=> '134', 'nombre' => 'Cantaclaro']);
DB::table('municipio')->insert([ 'id_municipio'=> '134', 'nombre' => 'San Juan de los Morros']);
DB::table('municipio')->insert([ 'id_municipio'=> '134', 'nombre' => 'Parapara']);
DB::table('municipio')->insert([ 'id_municipio'=> '135', 'nombre' => 'El Sombrero']);
DB::table('municipio')->insert([ 'id_municipio'=> '135', 'nombre' => 'Sosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '136', 'nombre' => 'Las Mercedes']);
DB::table('municipio')->insert([ 'id_municipio'=> '136', 'nombre' => 'Cabruta']);
DB::table('municipio')->insert([ 'id_municipio'=> '136', 'nombre' => 'Santa Rita de Manapire']);
DB::table('municipio')->insert([ 'id_municipio'=> '137', 'nombre' => 'Valle de la Pascua']);
DB::table('municipio')->insert([ 'id_municipio'=> '137', 'nombre' => 'Espino']);
DB::table('municipio')->insert([ 'id_municipio'=> '138', 'nombre' => 'San José de Unare']);
DB::table('municipio')->insert([ 'id_municipio'=> '138', 'nombre' => 'Zaraza']);
DB::table('municipio')->insert([ 'id_municipio'=> '139', 'nombre' => 'San José de Tiznados']);
DB::table('municipio')->insert([ 'id_municipio'=> '139', 'nombre' => 'San Francisco de Tiznados']);
DB::table('municipio')->insert([ 'id_municipio'=> '139', 'nombre' => 'San Lorenzo de Tiznados']);
DB::table('municipio')->insert([ 'id_municipio'=> '139', 'nombre' => 'Ortiz']);
DB::table('municipio')->insert([ 'id_municipio'=> '140', 'nombre' => 'Guayabal']);
DB::table('municipio')->insert([ 'id_municipio'=> '140', 'nombre' => 'Cazorla']);
DB::table('municipio')->insert([ 'id_municipio'=> '141', 'nombre' => 'San José de Guaribe']);
DB::table('municipio')->insert([ 'id_municipio'=> '141', 'nombre' => 'Uveral']);
DB::table('municipio')->insert([ 'id_municipio'=> '142', 'nombre' => 'Santa María de Ipire']);
DB::table('municipio')->insert([ 'id_municipio'=> '142', 'nombre' => 'Altamira']);
DB::table('municipio')->insert([ 'id_municipio'=> '143', 'nombre' => 'El Calvario']);
DB::table('municipio')->insert([ 'id_municipio'=> '143', 'nombre' => 'El Rastro']);
DB::table('municipio')->insert([ 'id_municipio'=> '143', 'nombre' => 'Guardatinajas']);
DB::table('municipio')->insert([ 'id_municipio'=> '143', 'nombre' => 'Capital Urbana Calabozo']);
DB::table('municipio')->insert([ 'id_municipio'=> '144', 'nombre' => 'Quebrada Honda de Guache']);
DB::table('municipio')->insert([ 'id_municipio'=> '144', 'nombre' => 'Pío Tamayo']);
DB::table('municipio')->insert([ 'id_municipio'=> '144', 'nombre' => 'Yacambú']);
DB::table('municipio')->insert([ 'id_municipio'=> '145', 'nombre' => 'Fréitez']);
DB::table('municipio')->insert([ 'id_municipio'=> '145', 'nombre' => 'José María Blanco']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Catedral']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Concepción']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'El Cují']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Juan de Villegas']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Santa Rosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Tamaca']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Unión']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Aguedo Felipe Alvarado']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Buena Vista']);
DB::table('municipio')->insert([ 'id_municipio'=> '146', 'nombre' => 'Juárez']);
DB::table('municipio')->insert([ 'id_municipio'=> '147', 'nombre' => 'Juan Bautista Rodríguez']);
DB::table('municipio')->insert([ 'id_municipio'=> '147', 'nombre' => 'Cuara']);
DB::table('municipio')->insert([ 'id_municipio'=> '147', 'nombre' => 'Diego de Lozada']);
DB::table('municipio')->insert([ 'id_municipio'=> '147', 'nombre' => 'Paraíso de San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '147', 'nombre' => 'San Miguel']);
DB::table('municipio')->insert([ 'id_municipio'=> '147', 'nombre' => 'Tintorero']);
DB::table('municipio')->insert([ 'id_municipio'=> '147', 'nombre' => 'José Bernardo Dorante']);
DB::table('municipio')->insert([ 'id_municipio'=> '147', 'nombre' => 'Coronel Mariano Peraza ']);
DB::table('municipio')->insert([ 'id_municipio'=> '148', 'nombre' => 'Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '148', 'nombre' => 'Anzoátegui']);
DB::table('municipio')->insert([ 'id_municipio'=> '148', 'nombre' => 'Guarico']);
DB::table('municipio')->insert([ 'id_municipio'=> '148', 'nombre' => 'Hilario Luna y Luna']);
DB::table('municipio')->insert([ 'id_municipio'=> '148', 'nombre' => 'Humocaro Alto']);
DB::table('municipio')->insert([ 'id_municipio'=> '148', 'nombre' => 'Humocaro Bajo']);
DB::table('municipio')->insert([ 'id_municipio'=> '148', 'nombre' => 'La Candelaria']);
DB::table('municipio')->insert([ 'id_municipio'=> '148', 'nombre' => 'Morán']);
DB::table('municipio')->insert([ 'id_municipio'=> '149', 'nombre' => 'Cabudare']);
DB::table('municipio')->insert([ 'id_municipio'=> '149', 'nombre' => 'José Gregorio Bastidas']);
DB::table('municipio')->insert([ 'id_municipio'=> '149', 'nombre' => 'Agua Viva']);
DB::table('municipio')->insert([ 'id_municipio'=> '150', 'nombre' => 'Sarare']);
DB::table('municipio')->insert([ 'id_municipio'=> '150', 'nombre' => 'Buría']);
DB::table('municipio')->insert([ 'id_municipio'=> '150', 'nombre' => 'Gustavo Vegas León']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Trinidad Samuel']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Antonio Díaz']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Camacaro']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Castañeda']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Cecilio Zubillaga']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Chiquinquirá']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'El Blanco']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Espinoza de los Monteros']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Lara']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Las Mercedes']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Manuel Morillo']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Montaña Verde']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Montes de Oca']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Torres']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Heriberto Arroyo']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Reyes Vargas']);
DB::table('municipio')->insert([ 'id_municipio'=> '151', 'nombre' => 'Altagracia']);
DB::table('municipio')->insert([ 'id_municipio'=> '152', 'nombre' => 'Siquisique']);
DB::table('municipio')->insert([ 'id_municipio'=> '152', 'nombre' => 'Moroturo']);
DB::table('municipio')->insert([ 'id_municipio'=> '152', 'nombre' => 'San Miguel']);
DB::table('municipio')->insert([ 'id_municipio'=> '152', 'nombre' => 'Xaguas']);
DB::table('municipio')->insert([ 'id_municipio'=> '153', 'nombre' => 'Presidente Betancourt']);
DB::table('municipio')->insert([ 'id_municipio'=> '153', 'nombre' => 'Presidente Páez']);
DB::table('municipio')->insert([ 'id_municipio'=> '153', 'nombre' => 'Presidente Rómulo Gallegos']);
DB::table('municipio')->insert([ 'id_municipio'=> '153', 'nombre' => 'Gabriel Picón González']);
DB::table('municipio')->insert([ 'id_municipio'=> '153', 'nombre' => 'Héctor Amable Mora']);
DB::table('municipio')->insert([ 'id_municipio'=> '153', 'nombre' => 'José Nucete Sardi']);
DB::table('municipio')->insert([ 'id_municipio'=> '153', 'nombre' => 'Pulido Méndez']);
DB::table('municipio')->insert([ 'id_municipio'=> '154', 'nombre' => 'La Azulita']);
DB::table('municipio')->insert([ 'id_municipio'=> '155', 'nombre' => 'Santa Cruz de Mora']);
DB::table('municipio')->insert([ 'id_municipio'=> '155', 'nombre' => 'Mesa Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '155', 'nombre' => 'Mesa de Las Palmas']);
DB::table('municipio')->insert([ 'id_municipio'=> '156', 'nombre' => 'Aricagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '156', 'nombre' => 'San Antonio']);
DB::table('municipio')->insert([ 'id_municipio'=> '157', 'nombre' => 'Canagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '157', 'nombre' => 'Capurí']);
DB::table('municipio')->insert([ 'id_municipio'=> '157', 'nombre' => 'Chacantá']);
DB::table('municipio')->insert([ 'id_municipio'=> '157', 'nombre' => 'El Molino']);
DB::table('municipio')->insert([ 'id_municipio'=> '157', 'nombre' => 'Guaimaral']);
DB::table('municipio')->insert([ 'id_municipio'=> '157', 'nombre' => 'Mucutuy']);
DB::table('municipio')->insert([ 'id_municipio'=> '157', 'nombre' => 'Mucuchachí']);
DB::table('municipio')->insert([ 'id_municipio'=> '158', 'nombre' => 'Fernández Peña']);
DB::table('municipio')->insert([ 'id_municipio'=> '158', 'nombre' => 'Matriz']);
DB::table('municipio')->insert([ 'id_municipio'=> '158', 'nombre' => 'Montalbán']);
DB::table('municipio')->insert([ 'id_municipio'=> '158', 'nombre' => 'Acequias']);
DB::table('municipio')->insert([ 'id_municipio'=> '158', 'nombre' => 'Jají']);
DB::table('municipio')->insert([ 'id_municipio'=> '158', 'nombre' => 'La Mesa']);
DB::table('municipio')->insert([ 'id_municipio'=> '158', 'nombre' => 'San José del Sur']);
DB::table('municipio')->insert([ 'id_municipio'=> '159', 'nombre' => 'Tucaní']);
DB::table('municipio')->insert([ 'id_municipio'=> '159', 'nombre' => 'Florencio Ramírez']);
DB::table('municipio')->insert([ 'id_municipio'=> '160', 'nombre' => 'Santo Domingo']);
DB::table('municipio')->insert([ 'id_municipio'=> '160', 'nombre' => 'Las Piedras']);
DB::table('municipio')->insert([ 'id_municipio'=> '161', 'nombre' => 'Guaraque']);
DB::table('municipio')->insert([ 'id_municipio'=> '161', 'nombre' => 'Mesa de Quintero']);
DB::table('municipio')->insert([ 'id_municipio'=> '161', 'nombre' => 'Río Negro']);
DB::table('municipio')->insert([ 'id_municipio'=> '162', 'nombre' => 'Arapuey']);
DB::table('municipio')->insert([ 'id_municipio'=> '162', 'nombre' => 'Palmira']);
DB::table('municipio')->insert([ 'id_municipio'=> '163', 'nombre' => 'San Cristóbal de Torondoy']);
DB::table('municipio')->insert([ 'id_municipio'=> '163', 'nombre' => 'Torondoy']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Antonio Spinetti Dini']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Arias']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Caracciolo Parra Pérez']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Domingo Peña']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'El Llano']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Gonzalo Picón Febres']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Jacinto Plaza']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Juan Rodríguez Suárez']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Lasso de la Vega']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Mariano Picón Salas']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Milla']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Osuna Rodríguez']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Sagrario']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'El Morro']);
DB::table('municipio')->insert([ 'id_municipio'=> '164', 'nombre' => 'Los Nevados']);
DB::table('municipio')->insert([ 'id_municipio'=> '165', 'nombre' => 'Andrés Eloy Blanco']);
DB::table('municipio')->insert([ 'id_municipio'=> '165', 'nombre' => 'La Venta']);
DB::table('municipio')->insert([ 'id_municipio'=> '165', 'nombre' => 'Piñango']);
DB::table('municipio')->insert([ 'id_municipio'=> '165', 'nombre' => 'Timotes']);
DB::table('municipio')->insert([ 'id_municipio'=> '166', 'nombre' => 'Eloy Paredes']);
DB::table('municipio')->insert([ 'id_municipio'=> '166', 'nombre' => 'San Rafael de Alcázar']);
DB::table('municipio')->insert([ 'id_municipio'=> '166', 'nombre' => 'Santa Elena de Arenales']);
DB::table('municipio')->insert([ 'id_municipio'=> '167', 'nombre' => 'Santa María de Caparo']);
DB::table('municipio')->insert([ 'id_municipio'=> '168', 'nombre' => 'Pueblo Llano']);
DB::table('municipio')->insert([ 'id_municipio'=> '169', 'nombre' => 'Cacute']);
DB::table('municipio')->insert([ 'id_municipio'=> '169', 'nombre' => 'La Toma']);
DB::table('municipio')->insert([ 'id_municipio'=> '169', 'nombre' => 'Mucuchíes']);
DB::table('municipio')->insert([ 'id_municipio'=> '169', 'nombre' => 'Mucurubá']);
DB::table('municipio')->insert([ 'id_municipio'=> '169', 'nombre' => 'San Rafael']);
DB::table('municipio')->insert([ 'id_municipio'=> '170', 'nombre' => 'Gerónimo Maldonado']);
DB::table('municipio')->insert([ 'id_municipio'=> '170', 'nombre' => 'Bailadores']);
DB::table('municipio')->insert([ 'id_municipio'=> '171', 'nombre' => 'Tabay']);
DB::table('municipio')->insert([ 'id_municipio'=> '172', 'nombre' => 'Chiguará']);
DB::table('municipio')->insert([ 'id_municipio'=> '172', 'nombre' => 'Estánquez']);
DB::table('municipio')->insert([ 'id_municipio'=> '172', 'nombre' => 'Lagunillas']);
DB::table('municipio')->insert([ 'id_municipio'=> '172', 'nombre' => 'La Trampa']);
DB::table('municipio')->insert([ 'id_municipio'=> '172', 'nombre' => 'Pueblo Nuevo del Sur']);
DB::table('municipio')->insert([ 'id_municipio'=> '172', 'nombre' => 'San Juan']);
DB::table('municipio')->insert([ 'id_municipio'=> '173', 'nombre' => 'El Amparo']);
DB::table('municipio')->insert([ 'id_municipio'=> '173', 'nombre' => 'El Llano']);
DB::table('municipio')->insert([ 'id_municipio'=> '173', 'nombre' => 'San Francisco']);
DB::table('municipio')->insert([ 'id_municipio'=> '173', 'nombre' => 'Tovar']);
DB::table('municipio')->insert([ 'id_municipio'=> '174', 'nombre' => 'Independencia']);
DB::table('municipio')->insert([ 'id_municipio'=> '174', 'nombre' => 'María de la Concepción Palacios Blanco']);
DB::table('municipio')->insert([ 'id_municipio'=> '174', 'nombre' => 'Nueva Bolivia']);
DB::table('municipio')->insert([ 'id_municipio'=> '174', 'nombre' => 'Santa Apolonia']);
DB::table('municipio')->insert([ 'id_municipio'=> '175', 'nombre' => 'Caño El Tigre']);
DB::table('municipio')->insert([ 'id_municipio'=> '175', 'nombre' => 'Zea']);
DB::table('municipio')->insert([ 'id_municipio'=> '176', 'nombre' => 'Aragüita']);
DB::table('municipio')->insert([ 'id_municipio'=> '176', 'nombre' => 'Arévalo González']);
DB::table('municipio')->insert([ 'id_municipio'=> '176', 'nombre' => 'Capaya']);
DB::table('municipio')->insert([ 'id_municipio'=> '176', 'nombre' => 'Caucagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '176', 'nombre' => 'Panaquire']);
DB::table('municipio')->insert([ 'id_municipio'=> '176', 'nombre' => 'Ribas']);
DB::table('municipio')->insert([ 'id_municipio'=> '176', 'nombre' => 'El Café']);
DB::table('municipio')->insert([ 'id_municipio'=> '176', 'nombre' => 'Marizapa']);
DB::table('municipio')->insert([ 'id_municipio'=> '177', 'nombre' => 'Cumbo']);
DB::table('municipio')->insert([ 'id_municipio'=> '177', 'nombre' => 'San José de Barlovento']);
DB::table('municipio')->insert([ 'id_municipio'=> '178', 'nombre' => 'El Cafetal']);
DB::table('municipio')->insert([ 'id_municipio'=> '178', 'nombre' => 'Las Minas']);
DB::table('municipio')->insert([ 'id_municipio'=> '178', 'nombre' => 'Nuestra Señora del Rosario']);
DB::table('municipio')->insert([ 'id_municipio'=> '179', 'nombre' => 'Higuerote']);
DB::table('municipio')->insert([ 'id_municipio'=> '179', 'nombre' => 'Curiepe']);
DB::table('municipio')->insert([ 'id_municipio'=> '179', 'nombre' => 'Tacarigua de Brión']);
DB::table('municipio')->insert([ 'id_municipio'=> '180', 'nombre' => 'Mamporal']);
DB::table('municipio')->insert([ 'id_municipio'=> '181', 'nombre' => 'Carrizal']);
DB::table('municipio')->insert([ 'id_municipio'=> '182', 'nombre' => 'Chacao']);
DB::table('municipio')->insert([ 'id_municipio'=> '183', 'nombre' => 'Charallave']);
DB::table('municipio')->insert([ 'id_municipio'=> '183', 'nombre' => 'Las Brisas']);
DB::table('municipio')->insert([ 'id_municipio'=> '184', 'nombre' => 'El Hatillo']);
DB::table('municipio')->insert([ 'id_municipio'=> '185', 'nombre' => 'Altagracia de la Montaña']);
DB::table('municipio')->insert([ 'id_municipio'=> '185', 'nombre' => 'Cecilio Acosta']);
DB::table('municipio')->insert([ 'id_municipio'=> '185', 'nombre' => 'Los Teques']);
DB::table('municipio')->insert([ 'id_municipio'=> '185', 'nombre' => 'El Jarillo']);
DB::table('municipio')->insert([ 'id_municipio'=> '185', 'nombre' => 'San Pedro']);
DB::table('municipio')->insert([ 'id_municipio'=> '185', 'nombre' => 'Tácata']);
DB::table('municipio')->insert([ 'id_municipio'=> '185', 'nombre' => 'Paracotos']);
DB::table('municipio')->insert([ 'id_municipio'=> '186', 'nombre' => 'Cartanal']);
DB::table('municipio')->insert([ 'id_municipio'=> '186', 'nombre' => 'Santa Teresa del Tuy']);
DB::table('municipio')->insert([ 'id_municipio'=> '187', 'nombre' => 'La Democracia']);
DB::table('municipio')->insert([ 'id_municipio'=> '187', 'nombre' => 'Ocumare del Tuy']);
DB::table('municipio')->insert([ 'id_municipio'=> '187', 'nombre' => 'Santa Bárbara']);
DB::table('municipio')->insert([ 'id_municipio'=> '188', 'nombre' => 'San Antonio de los Altos']);
DB::table('municipio')->insert([ 'id_municipio'=> '189', 'nombre' => 'Río Chico']);
DB::table('municipio')->insert([ 'id_municipio'=> '189', 'nombre' => 'El Guapo']);
DB::table('municipio')->insert([ 'id_municipio'=> '189', 'nombre' => 'Tacarigua de la Laguna']);
DB::table('municipio')->insert([ 'id_municipio'=> '189', 'nombre' => 'Paparo']);
DB::table('municipio')->insert([ 'id_municipio'=> '189', 'nombre' => 'San Fernando del Guapo']);
DB::table('municipio')->insert([ 'id_municipio'=> '190', 'nombre' => 'Santa Lucía del Tuy']);
DB::table('municipio')->insert([ 'id_municipio'=> '191', 'nombre' => 'Cúpira']);
DB::table('municipio')->insert([ 'id_municipio'=> '191', 'nombre' => 'Machurucuto']);
DB::table('municipio')->insert([ 'id_municipio'=> '192', 'nombre' => 'Guarenas']);
DB::table('municipio')->insert([ 'id_municipio'=> '193', 'nombre' => 'San Antonio de Yare']);
DB::table('municipio')->insert([ 'id_municipio'=> '193', 'nombre' => 'San Francisco de Yare']);
DB::table('municipio')->insert([ 'id_municipio'=> '194', 'nombre' => 'Leoncio Martínez']);
DB::table('municipio')->insert([ 'id_municipio'=> '194', 'nombre' => 'Petare']);
DB::table('municipio')->insert([ 'id_municipio'=> '194', 'nombre' => 'Caucagüita']);
DB::table('municipio')->insert([ 'id_municipio'=> '194', 'nombre' => 'Filas de Mariche']);
DB::table('municipio')->insert([ 'id_municipio'=> '194', 'nombre' => 'La Dolorita']);
DB::table('municipio')->insert([ 'id_municipio'=> '195', 'nombre' => 'Cúa']);
DB::table('municipio')->insert([ 'id_municipio'=> '195', 'nombre' => 'Nueva Cúa']);
DB::table('municipio')->insert([ 'id_municipio'=> '196', 'nombre' => 'Guatire']);
DB::table('municipio')->insert([ 'id_municipio'=> '196', 'nombre' => 'Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '197', 'nombre' => 'San Antonio de Maturín']);
DB::table('municipio')->insert([ 'id_municipio'=> '197', 'nombre' => 'San Francisco de Maturín']);
DB::table('municipio')->insert([ 'id_municipio'=> '198', 'nombre' => 'Aguasay']);
DB::table('municipio')->insert([ 'id_municipio'=> '199', 'nombre' => 'Caripito']);
DB::table('municipio')->insert([ 'id_municipio'=> '200', 'nombre' => 'El Guácharo']);
DB::table('municipio')->insert([ 'id_municipio'=> '200', 'nombre' => 'La Guanota']);
DB::table('municipio')->insert([ 'id_municipio'=> '200', 'nombre' => 'Sabana de Piedra']);
DB::table('municipio')->insert([ 'id_municipio'=> '200', 'nombre' => 'San Agustín']);
DB::table('municipio')->insert([ 'id_municipio'=> '200', 'nombre' => 'Teresen']);
DB::table('municipio')->insert([ 'id_municipio'=> '200', 'nombre' => 'Caripe']);
DB::table('municipio')->insert([ 'id_municipio'=> '201', 'nombre' => 'Areo']);
DB::table('municipio')->insert([ 'id_municipio'=> '201', 'nombre' => 'Capital Cedeño']);
DB::table('municipio')->insert([ 'id_municipio'=> '201', 'nombre' => 'San Félix de Cantalicio']);
DB::table('municipio')->insert([ 'id_municipio'=> '201', 'nombre' => 'Viento Fresco']);
DB::table('municipio')->insert([ 'id_municipio'=> '202', 'nombre' => 'El Tejero']);
DB::table('municipio')->insert([ 'id_municipio'=> '202', 'nombre' => 'Punta de Mata']);
DB::table('municipio')->insert([ 'id_municipio'=> '203', 'nombre' => 'Chaguaramas']);
DB::table('municipio')->insert([ 'id_municipio'=> '203', 'nombre' => 'Las Alhuacas']);
DB::table('municipio')->insert([ 'id_municipio'=> '203', 'nombre' => 'Tabasca']);
DB::table('municipio')->insert([ 'id_municipio'=> '203', 'nombre' => 'Temblador']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'Alto de los Godos']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'Boquerón']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'Las Cocuizas']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'La Cruz']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'San Simón']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'El Corozo']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'El Furrial']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'Jusepín']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'La Pica']);
DB::table('municipio')->insert([ 'id_municipio'=> '204', 'nombre' => 'San Vicente']);
DB::table('municipio')->insert([ 'id_municipio'=> '205', 'nombre' => 'Aparicio']);
DB::table('municipio')->insert([ 'id_municipio'=> '205', 'nombre' => 'Aragua de Maturín']);
DB::table('municipio')->insert([ 'id_municipio'=> '205', 'nombre' => 'Chaguamal']);
DB::table('municipio')->insert([ 'id_municipio'=> '205', 'nombre' => 'El Pinto']);
DB::table('municipio')->insert([ 'id_municipio'=> '205', 'nombre' => 'Guanaguana']);
DB::table('municipio')->insert([ 'id_municipio'=> '205', 'nombre' => 'La Toscana']);
DB::table('municipio')->insert([ 'id_municipio'=> '205', 'nombre' => 'Taguaya']);
DB::table('municipio')->insert([ 'id_municipio'=> '206', 'nombre' => 'Cachipo']);
DB::table('municipio')->insert([ 'id_municipio'=> '206', 'nombre' => 'Quiriquire']);
DB::table('municipio')->insert([ 'id_municipio'=> '207', 'nombre' => 'Santa Bárbara']);
DB::table('municipio')->insert([ 'id_municipio'=> '208', 'nombre' => 'Barrancas']);
DB::table('municipio')->insert([ 'id_municipio'=> '208', 'nombre' => 'Los Barrancos de Fajardo']);
DB::table('municipio')->insert([ 'id_municipio'=> '209', 'nombre' => 'Uracoa']);
DB::table('municipio')->insert([ 'id_municipio'=> '210', 'nombre' => 'Antolín del Campo']);
DB::table('municipio')->insert([ 'id_municipio'=> '211', 'nombre' => 'Arismendi']);
DB::table('municipio')->insert([ 'id_municipio'=> '212', 'nombre' => 'García']);
DB::table('municipio')->insert([ 'id_municipio'=> '212', 'nombre' => 'Francisco Fajardo']);
DB::table('municipio')->insert([ 'id_municipio'=> '213', 'nombre' => 'Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '213', 'nombre' => 'Guevara']);
DB::table('municipio')->insert([ 'id_municipio'=> '213', 'nombre' => 'Matasiete']);
DB::table('municipio')->insert([ 'id_municipio'=> '213', 'nombre' => 'Santa Ana']);
DB::table('municipio')->insert([ 'id_municipio'=> '213', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '214', 'nombre' => 'Aguirre']);
DB::table('municipio')->insert([ 'id_municipio'=> '214', 'nombre' => 'Maneiro']);
DB::table('municipio')->insert([ 'id_municipio'=> '215', 'nombre' => 'Adrián']);
DB::table('municipio')->insert([ 'id_municipio'=> '215', 'nombre' => 'Juan Griego']);
DB::table('municipio')->insert([ 'id_municipio'=> '215', 'nombre' => 'Yaguaraparo']);
DB::table('municipio')->insert([ 'id_municipio'=> '216', 'nombre' => 'Porlamar']);
DB::table('municipio')->insert([ 'id_municipio'=> '217', 'nombre' => 'San Francisco de Macanao']);
DB::table('municipio')->insert([ 'id_municipio'=> '217', 'nombre' => 'Boca de Río']);
DB::table('municipio')->insert([ 'id_municipio'=> '218', 'nombre' => 'Tubores']);
DB::table('municipio')->insert([ 'id_municipio'=> '218', 'nombre' => 'Los Baleales']);
DB::table('municipio')->insert([ 'id_municipio'=> '219', 'nombre' => 'Vicente Fuentes']);
DB::table('municipio')->insert([ 'id_municipio'=> '219', 'nombre' => 'Villalba']);
DB::table('municipio')->insert([ 'id_municipio'=> '220', 'nombre' => 'San Juan Bautista']);
DB::table('municipio')->insert([ 'id_municipio'=> '220', 'nombre' => 'Zabala']);
DB::table('municipio')->insert([ 'id_municipio'=> '222', 'nombre' => 'Capital Araure']);
DB::table('municipio')->insert([ 'id_municipio'=> '222', 'nombre' => 'Río Acarigua']);
DB::table('municipio')->insert([ 'id_municipio'=> '223', 'nombre' => 'Capital Esteller']);
DB::table('municipio')->insert([ 'id_municipio'=> '223', 'nombre' => 'Uveral']);
DB::table('municipio')->insert([ 'id_municipio'=> '224', 'nombre' => 'Guanare']);
DB::table('municipio')->insert([ 'id_municipio'=> '224', 'nombre' => 'Córdoba']);
DB::table('municipio')->insert([ 'id_municipio'=> '224', 'nombre' => 'San José de la Montaña']);
DB::table('municipio')->insert([ 'id_municipio'=> '224', 'nombre' => 'San Juan de Guanaguanare']);
DB::table('municipio')->insert([ 'id_municipio'=> '224', 'nombre' => 'Virgen de la Coromoto']);
DB::table('municipio')->insert([ 'id_municipio'=> '225', 'nombre' => 'Guanarito']);
DB::table('municipio')->insert([ 'id_municipio'=> '225', 'nombre' => 'Trinidad de la Capilla']);
DB::table('municipio')->insert([ 'id_municipio'=> '225', 'nombre' => 'Divina Pastora']);
DB::table('municipio')->insert([ 'id_municipio'=> '226', 'nombre' => 'Monseñor José Vicente de Unda']);
DB::table('municipio')->insert([ 'id_municipio'=> '226', 'nombre' => 'Peña Blanca']);
DB::table('municipio')->insert([ 'id_municipio'=> '227', 'nombre' => 'Capital Ospino']);
DB::table('municipio')->insert([ 'id_municipio'=> '227', 'nombre' => 'Aparición']);
DB::table('municipio')->insert([ 'id_municipio'=> '227', 'nombre' => 'La Estación']);
DB::table('municipio')->insert([ 'id_municipio'=> '228', 'nombre' => 'Páez']);
DB::table('municipio')->insert([ 'id_municipio'=> '228', 'nombre' => 'Payara']);
DB::table('municipio')->insert([ 'id_municipio'=> '228', 'nombre' => 'Pimpinela']);
DB::table('municipio')->insert([ 'id_municipio'=> '228', 'nombre' => 'Ramón Peraza']);
DB::table('municipio')->insert([ 'id_municipio'=> '229', 'nombre' => 'Papelón']);
DB::table('municipio')->insert([ 'id_municipio'=> '229', 'nombre' => 'Caño Delgadito']);
DB::table('municipio')->insert([ 'id_municipio'=> '230', 'nombre' => 'San Genaro de Boconoito']);
DB::table('municipio')->insert([ 'id_municipio'=> '230', 'nombre' => 'Antolín Tovar']);
DB::table('municipio')->insert([ 'id_municipio'=> '231', 'nombre' => 'San Rafael de Onoto']);
DB::table('municipio')->insert([ 'id_municipio'=> '231', 'nombre' => 'Santa Fe']);
DB::table('municipio')->insert([ 'id_municipio'=> '231', 'nombre' => 'Thermo Morles']);
DB::table('municipio')->insert([ 'id_municipio'=> '232', 'nombre' => 'Santa Rosalía']);
DB::table('municipio')->insert([ 'id_municipio'=> '232', 'nombre' => 'Florida']);
DB::table('municipio')->insert([ 'id_municipio'=> '233', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '233', 'nombre' => 'Concepción']);
DB::table('municipio')->insert([ 'id_municipio'=> '233', 'nombre' => 'San Rafael de Palo Alzado']);
DB::table('municipio')->insert([ 'id_municipio'=> '233', 'nombre' => 'Uvencio Antonio Velásquez']);
DB::table('municipio')->insert([ 'id_municipio'=> '233', 'nombre' => 'San José de Saguaz']);
DB::table('municipio')->insert([ 'id_municipio'=> '233', 'nombre' => 'Villa Rosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '234', 'nombre' => 'Turén']);
DB::table('municipio')->insert([ 'id_municipio'=> '234', 'nombre' => 'Canelones']);
DB::table('municipio')->insert([ 'id_municipio'=> '234', 'nombre' => 'Santa Cruz']);
DB::table('municipio')->insert([ 'id_municipio'=> '234', 'nombre' => 'San Isidro Labrador']);
DB::table('municipio')->insert([ 'id_municipio'=> '235', 'nombre' => 'Mariño']);
DB::table('municipio')->insert([ 'id_municipio'=> '235', 'nombre' => 'Rómulo Gallegos']);
DB::table('municipio')->insert([ 'id_municipio'=> '236', 'nombre' => 'San José de Aerocuar']);
DB::table('municipio')->insert([ 'id_municipio'=> '236', 'nombre' => 'Tavera Acosta']);
DB::table('municipio')->insert([ 'id_municipio'=> '237', 'nombre' => 'Río Caribe']);
DB::table('municipio')->insert([ 'id_municipio'=> '237', 'nombre' => 'Antonio José de Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '237', 'nombre' => 'El Morro de Puerto Santo']);
DB::table('municipio')->insert([ 'id_municipio'=> '237', 'nombre' => 'Puerto Santo']);
DB::table('municipio')->insert([ 'id_municipio'=> '237', 'nombre' => 'San Juan de las Galdonas']);
DB::table('municipio')->insert([ 'id_municipio'=> '238', 'nombre' => 'El Pilar']);
DB::table('municipio')->insert([ 'id_municipio'=> '238', 'nombre' => 'El Rincón']);
DB::table('municipio')->insert([ 'id_municipio'=> '238', 'nombre' => 'General Francisco Antonio Váquez']);
DB::table('municipio')->insert([ 'id_municipio'=> '238', 'nombre' => 'Guaraúnos']);
DB::table('municipio')->insert([ 'id_municipio'=> '238', 'nombre' => 'Tunapuicito']);
DB::table('municipio')->insert([ 'id_municipio'=> '238', 'nombre' => 'Unión']);
DB::table('municipio')->insert([ 'id_municipio'=> '239', 'nombre' => 'Santa Catalina']);
DB::table('municipio')->insert([ 'id_municipio'=> '239', 'nombre' => 'Santa Rosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '239', 'nombre' => 'Santa Teresa']);
DB::table('municipio')->insert([ 'id_municipio'=> '239', 'nombre' => 'Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '239', 'nombre' => 'Maracapana']);
DB::table('municipio')->insert([ 'id_municipio'=> '241', 'nombre' => 'Libertad']);
DB::table('municipio')->insert([ 'id_municipio'=> '241', 'nombre' => 'El Paujil']);
DB::table('municipio')->insert([ 'id_municipio'=> '241', 'nombre' => 'Yaguaraparo']);
DB::table('municipio')->insert([ 'id_municipio'=> '242', 'nombre' => 'Cruz Salmerón Acosta']);
DB::table('municipio')->insert([ 'id_municipio'=> '242', 'nombre' => 'Chacopata']);
DB::table('municipio')->insert([ 'id_municipio'=> '242', 'nombre' => 'Manicuare']);
DB::table('municipio')->insert([ 'id_municipio'=> '243', 'nombre' => 'Tunapuy']);
DB::table('municipio')->insert([ 'id_municipio'=> '243', 'nombre' => 'Campo Elías']);
DB::table('municipio')->insert([ 'id_municipio'=> '244', 'nombre' => 'Irapa']);
DB::table('municipio')->insert([ 'id_municipio'=> '244', 'nombre' => 'Campo Claro']);
DB::table('municipio')->insert([ 'id_municipio'=> '244', 'nombre' => 'Maraval']);
DB::table('municipio')->insert([ 'id_municipio'=> '244', 'nombre' => 'San Antonio de Irapa']);
DB::table('municipio')->insert([ 'id_municipio'=> '244', 'nombre' => 'Soro']);
DB::table('municipio')->insert([ 'id_municipio'=> '245', 'nombre' => 'Mejía']);
DB::table('municipio')->insert([ 'id_municipio'=> '246', 'nombre' => 'Cumanacoa']);
DB::table('municipio')->insert([ 'id_municipio'=> '246', 'nombre' => 'Arenas']);
DB::table('municipio')->insert([ 'id_municipio'=> '246', 'nombre' => 'Aricagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '246', 'nombre' => 'Cogollar']);
DB::table('municipio')->insert([ 'id_municipio'=> '246', 'nombre' => 'San Fernando']);
DB::table('municipio')->insert([ 'id_municipio'=> '246', 'nombre' => 'San Lorenzo']);
DB::table('municipio')->insert([ 'id_municipio'=> '247', 'nombre' => 'Villa Frontado']);
DB::table('municipio')->insert([ 'id_municipio'=> '247', 'nombre' => 'Catuaro']);
DB::table('municipio')->insert([ 'id_municipio'=> '247', 'nombre' => 'Rendón']);
DB::table('municipio')->insert([ 'id_municipio'=> '247', 'nombre' => 'San Cruz']);
DB::table('municipio')->insert([ 'id_municipio'=> '247', 'nombre' => 'Santa María']);
DB::table('municipio')->insert([ 'id_municipio'=> '248', 'nombre' => 'Altagracia']);
DB::table('municipio')->insert([ 'id_municipio'=> '248', 'nombre' => 'Santa Inés']);
DB::table('municipio')->insert([ 'id_municipio'=> '248', 'nombre' => 'Valentín Valiente']);
DB::table('municipio')->insert([ 'id_municipio'=> '248', 'nombre' => 'Ayacucho']);
DB::table('municipio')->insert([ 'id_municipio'=> '248', 'nombre' => 'San Juan']);
DB::table('municipio')->insert([ 'id_municipio'=> '248', 'nombre' => 'Raúl Leoni']);
DB::table('municipio')->insert([ 'id_municipio'=> '248', 'nombre' => 'Gran Mariscal']);
DB::table('municipio')->insert([ 'id_municipio'=> '249', 'nombre' => 'Cristóbal Colón']);
DB::table('municipio')->insert([ 'id_municipio'=> '249', 'nombre' => 'Bideau']);
DB::table('municipio')->insert([ 'id_municipio'=> '249', 'nombre' => 'Punta de Piedras']);
DB::table('municipio')->insert([ 'id_municipio'=> '249', 'nombre' => 'Güiria']);
DB::table('municipio')->insert([ 'id_municipio'=> '250', 'nombre' => 'Andrés Bello']);
DB::table('municipio')->insert([ 'id_municipio'=> '251', 'nombre' => 'Antonio Rómulo Costa']);
DB::table('municipio')->insert([ 'id_municipio'=> '252', 'nombre' => 'Ayacucho']);
DB::table('municipio')->insert([ 'id_municipio'=> '252', 'nombre' => 'Rivas Berti']);
DB::table('municipio')->insert([ 'id_municipio'=> '252', 'nombre' => 'San Pedro del Río']);
DB::table('municipio')->insert([ 'id_municipio'=> '253', 'nombre' => 'Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '253', 'nombre' => 'Palotal']);
DB::table('municipio')->insert([ 'id_municipio'=> '253', 'nombre' => 'General Juan Vicente Gómez']);
DB::table('municipio')->insert([ 'id_municipio'=> '253', 'nombre' => 'Isaías Medina Angarita']);
DB::table('municipio')->insert([ 'id_municipio'=> '254', 'nombre' => 'Cárdenas']);
DB::table('municipio')->insert([ 'id_municipio'=> '254', 'nombre' => 'Amenodoro Ángel Lamus']);
DB::table('municipio')->insert([ 'id_municipio'=> '254', 'nombre' => 'La Florida']);
DB::table('municipio')->insert([ 'id_municipio'=> '255', 'nombre' => 'Córdoba']);
DB::table('municipio')->insert([ 'id_municipio'=> '256', 'nombre' => 'Fernández Feo']);
DB::table('municipio')->insert([ 'id_municipio'=> '256', 'nombre' => 'Alberto Adriani']);
DB::table('municipio')->insert([ 'id_municipio'=> '256', 'nombre' => 'Santo Domingo']);
DB::table('municipio')->insert([ 'id_municipio'=> '257', 'nombre' => 'Francisco de Miranda']);
DB::table('municipio')->insert([ 'id_municipio'=> '258', 'nombre' => 'García de Hevia']);
DB::table('municipio')->insert([ 'id_municipio'=> '258', 'nombre' => 'Boca de Grita']);
DB::table('municipio')->insert([ 'id_municipio'=> '258', 'nombre' => 'José Antonio Páez']);
DB::table('municipio')->insert([ 'id_municipio'=> '259', 'nombre' => 'Guásimos']);
DB::table('municipio')->insert([ 'id_municipio'=> '260', 'nombre' => 'Independencia']);
DB::table('municipio')->insert([ 'id_municipio'=> '260', 'nombre' => 'Juan Germán Roscio']);
DB::table('municipio')->insert([ 'id_municipio'=> '260', 'nombre' => 'Román Cárdenas']);
DB::table('municipio')->insert([ 'id_municipio'=> '261', 'nombre' => 'Jáuregui']);
DB::table('municipio')->insert([ 'id_municipio'=> '261', 'nombre' => 'Emilio Constantino Guerrero']);
DB::table('municipio')->insert([ 'id_municipio'=> '261', 'nombre' => 'Monseñor Miguel Antonio Salas']);
DB::table('municipio')->insert([ 'id_municipio'=> '262', 'nombre' => 'José María Vargas']);
DB::table('municipio')->insert([ 'id_municipio'=> '263', 'nombre' => 'Junín']);
DB::table('municipio')->insert([ 'id_municipio'=> '263', 'nombre' => 'La Petrólea']);
DB::table('municipio')->insert([ 'id_municipio'=> '263', 'nombre' => 'Quinimarí']);
DB::table('municipio')->insert([ 'id_municipio'=> '263', 'nombre' => 'Bramón']);
DB::table('municipio')->insert([ 'id_municipio'=> '264', 'nombre' => 'Libertad']);
DB::table('municipio')->insert([ 'id_municipio'=> '264', 'nombre' => 'Cipriano Castro']);
DB::table('municipio')->insert([ 'id_municipio'=> '264', 'nombre' => 'Manuel Felipe Rugeles']);
DB::table('municipio')->insert([ 'id_municipio'=> '265', 'nombre' => 'Libertador']);
DB::table('municipio')->insert([ 'id_municipio'=> '265', 'nombre' => 'Doradas']);
DB::table('municipio')->insert([ 'id_municipio'=> '265', 'nombre' => 'Emeterio Ochoa']);
DB::table('municipio')->insert([ 'id_municipio'=> '265', 'nombre' => 'San Joaquín de Navay']);
DB::table('municipio')->insert([ 'id_municipio'=> '266', 'nombre' => 'Lobatera']);
DB::table('municipio')->insert([ 'id_municipio'=> '266', 'nombre' => 'Constitución']);
DB::table('municipio')->insert([ 'id_municipio'=> '267', 'nombre' => 'Michelena']);
DB::table('municipio')->insert([ 'id_municipio'=> '268', 'nombre' => 'Panamericano']);
DB::table('municipio')->insert([ 'id_municipio'=> '268', 'nombre' => 'La Palmita']);
DB::table('municipio')->insert([ 'id_municipio'=> '269', 'nombre' => 'Pedro María Ureña']);
DB::table('municipio')->insert([ 'id_municipio'=> '269', 'nombre' => 'Nueva Arcadia']);
DB::table('municipio')->insert([ 'id_municipio'=> '270', 'nombre' => 'Delicias']);
DB::table('municipio')->insert([ 'id_municipio'=> '270', 'nombre' => 'Pecaya']);
DB::table('municipio')->insert([ 'id_municipio'=> '271', 'nombre' => 'Samuel Darío Maldonado']);
DB::table('municipio')->insert([ 'id_municipio'=> '271', 'nombre' => 'Boconó']);
DB::table('municipio')->insert([ 'id_municipio'=> '271', 'nombre' => 'Hernández']);
DB::table('municipio')->insert([ 'id_municipio'=> '272', 'nombre' => 'La Concordia']);
DB::table('municipio')->insert([ 'id_municipio'=> '272', 'nombre' => 'San Juan Bautista']);
DB::table('municipio')->insert([ 'id_municipio'=> '272', 'nombre' => 'Pedro María Morantes']);
DB::table('municipio')->insert([ 'id_municipio'=> '272', 'nombre' => 'San Sebastián']);
DB::table('municipio')->insert([ 'id_municipio'=> '272', 'nombre' => 'Dr. Francisco Romero Lobo']);
DB::table('municipio')->insert([ 'id_municipio'=> '273', 'nombre' => 'Seboruco']);
DB::table('municipio')->insert([ 'id_municipio'=> '274', 'nombre' => 'Simón Rodríguez']);
DB::table('municipio')->insert([ 'id_municipio'=> '275', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '275', 'nombre' => 'Eleazar López Contreras']);
DB::table('municipio')->insert([ 'id_municipio'=> '275', 'nombre' => 'San Pablo']);
DB::table('municipio')->insert([ 'id_municipio'=> '276', 'nombre' => 'Torbes']);
DB::table('municipio')->insert([ 'id_municipio'=> '277', 'nombre' => 'Uribante']);
DB::table('municipio')->insert([ 'id_municipio'=> '277', 'nombre' => 'Cárdenas']);
DB::table('municipio')->insert([ 'id_municipio'=> '277', 'nombre' => 'Juan Pablo Peñalosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '277', 'nombre' => 'Potosí']);
DB::table('municipio')->insert([ 'id_municipio'=> '278', 'nombre' => 'San Judas Tadeo']);
DB::table('municipio')->insert([ 'id_municipio'=> '279', 'nombre' => 'Araguaney']);
DB::table('municipio')->insert([ 'id_municipio'=> '279', 'nombre' => 'El Jaguito']);
DB::table('municipio')->insert([ 'id_municipio'=> '279', 'nombre' => 'La Esperanza']);
DB::table('municipio')->insert([ 'id_municipio'=> '279', 'nombre' => 'Santa Isabel']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'Boconó']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'El Carmen']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'Mosquey']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'Ayacucho']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'Burbusay']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'General Ribas']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'Guaramacal']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'Vega de Guaramacal']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'Monseñor Jáuregui']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'Rafael Rangel']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'San Miguel']);
DB::table('municipio')->insert([ 'id_municipio'=> '280', 'nombre' => 'San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '281', 'nombre' => 'Sabana Grande']);
DB::table('municipio')->insert([ 'id_municipio'=> '281', 'nombre' => 'Cheregüé']);
DB::table('municipio')->insert([ 'id_municipio'=> '281', 'nombre' => 'Granados']);
DB::table('municipio')->insert([ 'id_municipio'=> '282', 'nombre' => 'Arnoldo Gabaldón']);
DB::table('municipio')->insert([ 'id_municipio'=> '282', 'nombre' => 'Bolivia']);
DB::table('municipio')->insert([ 'id_municipio'=> '282', 'nombre' => 'Carrillo']);
DB::table('municipio')->insert([ 'id_municipio'=> '282', 'nombre' => 'Cegarra']);
DB::table('municipio')->insert([ 'id_municipio'=> '282', 'nombre' => 'Chejendé']);
DB::table('municipio')->insert([ 'id_municipio'=> '282', 'nombre' => 'Manuel Salvador Ulloa']);
DB::table('municipio')->insert([ 'id_municipio'=> '282', 'nombre' => 'San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '283', 'nombre' => 'Carache']);
DB::table('municipio')->insert([ 'id_municipio'=> '283', 'nombre' => 'La Concepción']);
DB::table('municipio')->insert([ 'id_municipio'=> '283', 'nombre' => 'Cuicas']);
DB::table('municipio')->insert([ 'id_municipio'=> '283', 'nombre' => 'Panamericana']);
DB::table('municipio')->insert([ 'id_municipio'=> '283', 'nombre' => 'Santa Cruz']);
DB::table('municipio')->insert([ 'id_municipio'=> '284', 'nombre' => 'Escuque']);
DB::table('municipio')->insert([ 'id_municipio'=> '284', 'nombre' => 'La Unión']);
DB::table('municipio')->insert([ 'id_municipio'=> '284', 'nombre' => 'Santa Rita']);
DB::table('municipio')->insert([ 'id_municipio'=> '284', 'nombre' => 'Sabana Libre']);
DB::table('municipio')->insert([ 'id_municipio'=> '285', 'nombre' => 'El Socorro']);
DB::table('municipio')->insert([ 'id_municipio'=> '285', 'nombre' => 'Los Caprichos']);
DB::table('municipio')->insert([ 'id_municipio'=> '285', 'nombre' => 'Antonio José de Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '286', 'nombre' => 'Campo Elías']);
DB::table('municipio')->insert([ 'id_municipio'=> '286', 'nombre' => 'Arnoldo Gabaldón']);
DB::table('municipio')->insert([ 'id_municipio'=> '287', 'nombre' => 'Santa Apolonia']);
DB::table('municipio')->insert([ 'id_municipio'=> '287', 'nombre' => 'El Progreso']);
DB::table('municipio')->insert([ 'id_municipio'=> '287', 'nombre' => 'La Ceiba']);
DB::table('municipio')->insert([ 'id_municipio'=> '287', 'nombre' => 'Tres de Febrero']);
DB::table('municipio')->insert([ 'id_municipio'=> '288', 'nombre' => 'El Dividive']);
DB::table('municipio')->insert([ 'id_municipio'=> '288', 'nombre' => 'Agua Santa']);
DB::table('municipio')->insert([ 'id_municipio'=> '288', 'nombre' => 'Agua Caliente']);
DB::table('municipio')->insert([ 'id_municipio'=> '288', 'nombre' => 'El Cenizo']);
DB::table('municipio')->insert([ 'id_municipio'=> '288', 'nombre' => 'Valerita']);
DB::table('municipio')->insert([ 'id_municipio'=> '289', 'nombre' => 'Monte Carmelo']);
DB::table('municipio')->insert([ 'id_municipio'=> '289', 'nombre' => 'Buena Vista']);
DB::table('municipio')->insert([ 'id_municipio'=> '289', 'nombre' => 'Santa María del Horcón']);
DB::table('municipio')->insert([ 'id_municipio'=> '290', 'nombre' => 'Motatán']);
DB::table('municipio')->insert([ 'id_municipio'=> '290', 'nombre' => 'El Baño']);
DB::table('municipio')->insert([ 'id_municipio'=> '290', 'nombre' => 'Jalisco']);
DB::table('municipio')->insert([ 'id_municipio'=> '291', 'nombre' => 'Pampán']);
DB::table('municipio')->insert([ 'id_municipio'=> '291', 'nombre' => 'Flor de Patria']);
DB::table('municipio')->insert([ 'id_municipio'=> '291', 'nombre' => 'La Paz']);
DB::table('municipio')->insert([ 'id_municipio'=> '291', 'nombre' => 'Santa Ana']);
DB::table('municipio')->insert([ 'id_municipio'=> '292', 'nombre' => 'Pampanito']);
DB::table('municipio')->insert([ 'id_municipio'=> '292', 'nombre' => 'La Concepción']);
DB::table('municipio')->insert([ 'id_municipio'=> '292', 'nombre' => 'Pampanito II']);
DB::table('municipio')->insert([ 'id_municipio'=> '293', 'nombre' => 'Betijoque']);
DB::table('municipio')->insert([ 'id_municipio'=> '293', 'nombre' => 'José Gregorio Hernández']);
DB::table('municipio')->insert([ 'id_municipio'=> '293', 'nombre' => 'La Pueblita']);
DB::table('municipio')->insert([ 'id_municipio'=> '293', 'nombre' => 'Los Cedros']);
DB::table('municipio')->insert([ 'id_municipio'=> '294', 'nombre' => 'Carvajal']);
DB::table('municipio')->insert([ 'id_municipio'=> '294', 'nombre' => 'Campo Alegre']);
DB::table('municipio')->insert([ 'id_municipio'=> '294', 'nombre' => 'Antonio Nicolás Briceño']);
DB::table('municipio')->insert([ 'id_municipio'=> '294', 'nombre' => 'José Leonardo Suárez']);
DB::table('municipio')->insert([ 'id_municipio'=> '295', 'nombre' => 'Sabana de Mendoza']);
DB::table('municipio')->insert([ 'id_municipio'=> '295', 'nombre' => 'Junín']);
DB::table('municipio')->insert([ 'id_municipio'=> '295', 'nombre' => 'Valmore Rodríguez']);
DB::table('municipio')->insert([ 'id_municipio'=> '295', 'nombre' => 'El Paraíso']);
DB::table('municipio')->insert([ 'id_municipio'=> '296', 'nombre' => 'Andrés Linares']);
DB::table('municipio')->insert([ 'id_municipio'=> '296', 'nombre' => 'Chiquinquirá']);
DB::table('municipio')->insert([ 'id_municipio'=> '296', 'nombre' => 'Cristóbal Mendoza']);
DB::table('municipio')->insert([ 'id_municipio'=> '296', 'nombre' => 'Cruz Carrillo']);
DB::table('municipio')->insert([ 'id_municipio'=> '296', 'nombre' => 'Matriz']);
DB::table('municipio')->insert([ 'id_municipio'=> '296', 'nombre' => 'Monseñor Carrillo']);
DB::table('municipio')->insert([ 'id_municipio'=> '296', 'nombre' => 'Tres Esquinas']);
DB::table('municipio')->insert([ 'id_municipio'=> '297', 'nombre' => 'Cabimbú']);
DB::table('municipio')->insert([ 'id_municipio'=> '297', 'nombre' => 'Jajó']);
DB::table('municipio')->insert([ 'id_municipio'=> '297', 'nombre' => 'La Mesa de Esnujaque']);
DB::table('municipio')->insert([ 'id_municipio'=> '297', 'nombre' => 'Santiago']);
DB::table('municipio')->insert([ 'id_municipio'=> '297', 'nombre' => 'Tuñame']);
DB::table('municipio')->insert([ 'id_municipio'=> '297', 'nombre' => 'La Quebrada']);
DB::table('municipio')->insert([ 'id_municipio'=> '298', 'nombre' => 'Juan Ignacio Montilla']);
DB::table('municipio')->insert([ 'id_municipio'=> '298', 'nombre' => 'La Beatriz']);
DB::table('municipio')->insert([ 'id_municipio'=> '298', 'nombre' => 'La Puerta']);
DB::table('municipio')->insert([ 'id_municipio'=> '298', 'nombre' => 'Mendoza del Valle de Momboy']);
DB::table('municipio')->insert([ 'id_municipio'=> '298', 'nombre' => 'Mercedes Díaz']);
DB::table('municipio')->insert([ 'id_municipio'=> '298', 'nombre' => 'San Luis']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Caraballeda']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Carayaca']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Carlos Soublette']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Caruao Chuspa']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Catia La Mar']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'El Junko']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'La Guaira']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Macuto']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Maiquetía']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Naiguatá']);
DB::table('municipio')->insert([ 'id_municipio'=> '299', 'nombre' => 'Urimare']);
DB::table('municipio')->insert([ 'id_municipio'=> '300', 'nombre' => 'Arístides Bastidas']);
DB::table('municipio')->insert([ 'id_municipio'=> '301', 'nombre' => 'Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '302', 'nombre' => 'Chivacoa']);
DB::table('municipio')->insert([ 'id_municipio'=> '302', 'nombre' => 'Campo Elías']);
DB::table('municipio')->insert([ 'id_municipio'=> '303', 'nombre' => 'Cocorote']);
DB::table('municipio')->insert([ 'id_municipio'=> '304', 'nombre' => 'Independencia']);
DB::table('municipio')->insert([ 'id_municipio'=> '305', 'nombre' => 'José Antonio Páez']);
DB::table('municipio')->insert([ 'id_municipio'=> '306', 'nombre' => 'La Trinidad']);
DB::table('municipio')->insert([ 'id_municipio'=> '307', 'nombre' => 'Manuel Monge']);
DB::table('municipio')->insert([ 'id_municipio'=> '308', 'nombre' => 'Salóm']);
DB::table('municipio')->insert([ 'id_municipio'=> '308', 'nombre' => 'Temerla']);
DB::table('municipio')->insert([ 'id_municipio'=> '308', 'nombre' => 'Nirgua']);
DB::table('municipio')->insert([ 'id_municipio'=> '309', 'nombre' => 'San Andrés']);
DB::table('municipio')->insert([ 'id_municipio'=> '309', 'nombre' => 'Yaritagua']);
DB::table('municipio')->insert([ 'id_municipio'=> '310', 'nombre' => 'San Javier']);
DB::table('municipio')->insert([ 'id_municipio'=> '310', 'nombre' => 'Albarico']);
DB::table('municipio')->insert([ 'id_municipio'=> '310', 'nombre' => 'San Felipe']);
DB::table('municipio')->insert([ 'id_municipio'=> '311', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '312', 'nombre' => 'Urachiche']);
DB::table('municipio')->insert([ 'id_municipio'=> '313', 'nombre' => 'El Guayabo']);
DB::table('municipio')->insert([ 'id_municipio'=> '313', 'nombre' => 'Farriar']);
DB::table('municipio')->insert([ 'id_municipio'=> '314', 'nombre' => 'Isla de Toas']);
DB::table('municipio')->insert([ 'id_municipio'=> '314', 'nombre' => 'Monagas']);
DB::table('municipio')->insert([ 'id_municipio'=> '315', 'nombre' => 'San Timoteo']);
DB::table('municipio')->insert([ 'id_municipio'=> '315', 'nombre' => 'General Urdaneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '315', 'nombre' => 'Libertador']);
DB::table('municipio')->insert([ 'id_municipio'=> '315', 'nombre' => 'Marcelino Briceño']);
DB::table('municipio')->insert([ 'id_municipio'=> '315', 'nombre' => 'Pueblo Nuevo']);
DB::table('municipio')->insert([ 'id_municipio'=> '315', 'nombre' => 'Manuel Guanipa Matos']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'Ambrosio']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'Carmen Herrera']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'La Rosa']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'Germán Ríos Linares']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'San Benito']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'Rómulo Betancourt']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'Jorge Hernández']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'Punta Gorda']);
DB::table('municipio')->insert([ 'id_municipio'=> '316', 'nombre' => 'Arístides Calvani']);
DB::table('municipio')->insert([ 'id_municipio'=> '317', 'nombre' => 'Encontrados']);
DB::table('municipio')->insert([ 'id_municipio'=> '317', 'nombre' => 'Udón Pérez']);
DB::table('municipio')->insert([ 'id_municipio'=> '318', 'nombre' => 'Moralito']);
DB::table('municipio')->insert([ 'id_municipio'=> '318', 'nombre' => 'San Carlos del Zulia']);
DB::table('municipio')->insert([ 'id_municipio'=> '318', 'nombre' => 'Santa Cruz del Zulia']);
DB::table('municipio')->insert([ 'id_municipio'=> '318', 'nombre' => 'Santa Bárbara']);
DB::table('municipio')->insert([ 'id_municipio'=> '318', 'nombre' => 'Urribarrí']);
DB::table('municipio')->insert([ 'id_municipio'=> '319', 'nombre' => 'Carlos Quevedo']);
DB::table('municipio')->insert([ 'id_municipio'=> '319', 'nombre' => 'Francisco Javier Pulgar']);
DB::table('municipio')->insert([ 'id_municipio'=> '319', 'nombre' => 'Simón Rodríguez']);
DB::table('municipio')->insert([ 'id_municipio'=> '319', 'nombre' => 'Guamo-Gavilanes']);
DB::table('municipio')->insert([ 'id_municipio'=> '321', 'nombre' => 'La Concepción']);
DB::table('municipio')->insert([ 'id_municipio'=> '321', 'nombre' => 'San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '321', 'nombre' => 'Mariano Parra León']);
DB::table('municipio')->insert([ 'id_municipio'=> '321', 'nombre' => 'José Ramón Yépez']);
DB::table('municipio')->insert([ 'id_municipio'=> '322', 'nombre' => 'Jesús María Semprún']);
DB::table('municipio')->insert([ 'id_municipio'=> '322', 'nombre' => 'Barí']);
DB::table('municipio')->insert([ 'id_municipio'=> '323', 'nombre' => 'Concepción']);
DB::table('municipio')->insert([ 'id_municipio'=> '323', 'nombre' => 'Andrés Bello']);
DB::table('municipio')->insert([ 'id_municipio'=> '323', 'nombre' => 'Chiquinquirá']);
DB::table('municipio')->insert([ 'id_municipio'=> '323', 'nombre' => 'El Carmelo']);
DB::table('municipio')->insert([ 'id_municipio'=> '323', 'nombre' => 'Potreritos']);
DB::table('municipio')->insert([ 'id_municipio'=> '324', 'nombre' => 'Libertad']);
DB::table('municipio')->insert([ 'id_municipio'=> '324', 'nombre' => 'Alonso de Ojeda']);
DB::table('municipio')->insert([ 'id_municipio'=> '324', 'nombre' => 'Venezuela']);
DB::table('municipio')->insert([ 'id_municipio'=> '324', 'nombre' => 'Eleazar López Contreras']);
DB::table('municipio')->insert([ 'id_municipio'=> '324', 'nombre' => 'Campo Lara']);
DB::table('municipio')->insert([ 'id_municipio'=> '325', 'nombre' => 'Bartolomé de las Casas']);
DB::table('municipio')->insert([ 'id_municipio'=> '325', 'nombre' => 'Libertad']);
DB::table('municipio')->insert([ 'id_municipio'=> '325', 'nombre' => 'Río Negro']);
DB::table('municipio')->insert([ 'id_municipio'=> '325', 'nombre' => 'San José de Perijá']);
DB::table('municipio')->insert([ 'id_municipio'=> '326', 'nombre' => 'San Rafael']);
DB::table('municipio')->insert([ 'id_municipio'=> '326', 'nombre' => 'La Sierrita']);
DB::table('municipio')->insert([ 'id_municipio'=> '326', 'nombre' => 'Las Parcelas']);
DB::table('municipio')->insert([ 'id_municipio'=> '326', 'nombre' => 'Luis de Vicente']);
DB::table('municipio')->insert([ 'id_municipio'=> '326', 'nombre' => 'Monseñor Marcos Sergio Godoy']);
DB::table('municipio')->insert([ 'id_municipio'=> '326', 'nombre' => 'Ricaurte']);
DB::table('municipio')->insert([ 'id_municipio'=> '326', 'nombre' => 'Tamare']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Antonio Borjas Romero']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Bolívar']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Cacique Mara']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Carracciolo Parra Pérez']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Cecilio Acosta']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Cristo de Aranza']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Coquivacoa']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Chiquinquirá']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Francisco Eugenio Bustamante']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Idelfonzo Vásquez']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Juana de Ávila']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Luis Hurtado Higuera']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Manuel Dagnino']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Olegario Villalobos']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Raúl Leoni']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Santa Lucía']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'Venancio Pulgar']);
DB::table('municipio')->insert([ 'id_municipio'=> '327', 'nombre' => 'San Isidro']);
DB::table('municipio')->insert([ 'id_municipio'=> '328', 'nombre' => 'Altagracia']);
DB::table('municipio')->insert([ 'id_municipio'=> '328', 'nombre' => 'Faría']);
DB::table('municipio')->insert([ 'id_municipio'=> '328', 'nombre' => 'Ana María Campos']);
DB::table('municipio')->insert([ 'id_municipio'=> '328', 'nombre' => 'San Antonio']);
DB::table('municipio')->insert([ 'id_municipio'=> '328', 'nombre' => 'San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '329', 'nombre' => 'Donaldo García']);
DB::table('municipio')->insert([ 'id_municipio'=> '329', 'nombre' => 'El Rosario']);
DB::table('municipio')->insert([ 'id_municipio'=> '329', 'nombre' => 'Sixto Zambrano']);
DB::table('municipio')->insert([ 'id_municipio'=> '330', 'nombre' => 'San Francisco']);
DB::table('municipio')->insert([ 'id_municipio'=> '330', 'nombre' => 'El Bajo']);
DB::table('municipio')->insert([ 'id_municipio'=> '330', 'nombre' => 'Domitila Flores']);
DB::table('municipio')->insert([ 'id_municipio'=> '330', 'nombre' => 'Francisco Ochoa']);
DB::table('municipio')->insert([ 'id_municipio'=> '330', 'nombre' => 'Los Cortijos']);
DB::table('municipio')->insert([ 'id_municipio'=> '330', 'nombre' => 'Marcial Hernández']);
DB::table('municipio')->insert([ 'id_municipio'=> '331', 'nombre' => 'Santa Rita']);
DB::table('municipio')->insert([ 'id_municipio'=> '331', 'nombre' => 'El Mene']);
DB::table('municipio')->insert([ 'id_municipio'=> '331', 'nombre' => 'Pedro Lucas Urribarrí']);
DB::table('municipio')->insert([ 'id_municipio'=> '331', 'nombre' => 'José Cenobio Urribarrí']);
DB::table('municipio')->insert([ 'id_municipio'=> '332', 'nombre' => 'Rafael Maria Baralt']);
DB::table('municipio')->insert([ 'id_municipio'=> '332', 'nombre' => 'Manuel Manrique']);
DB::table('municipio')->insert([ 'id_municipio'=> '332', 'nombre' => 'Rafael Urdaneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '333', 'nombre' => 'Bobures']);
DB::table('municipio')->insert([ 'id_municipio'=> '333', 'nombre' => 'Gibraltar']);
DB::table('municipio')->insert([ 'id_municipio'=> '333', 'nombre' => 'Heras']);
DB::table('municipio')->insert([ 'id_municipio'=> '333', 'nombre' => 'Monseñor Arturo Álvarez']);
DB::table('municipio')->insert([ 'id_municipio'=> '333', 'nombre' => 'Rómulo Gallegos']);
DB::table('municipio')->insert([ 'id_municipio'=> '333', 'nombre' => 'El Batey']);
DB::table('municipio')->insert([ 'id_municipio'=> '334', 'nombre' => 'Rafael Urdaneta']);
DB::table('municipio')->insert([ 'id_municipio'=> '334', 'nombre' => 'La Victoria']);
DB::table('municipio')->insert([ 'id_municipio'=> '334', 'nombre' => 'Raúl Cuenca']);
DB::table('municipio')->insert([ 'id_municipio'=> '320', 'nombre' => 'Sinamaica']);
DB::table('municipio')->insert([ 'id_municipio'=> '320', 'nombre' => 'Alta Guajira']);
DB::table('municipio')->insert([ 'id_municipio'=> '320', 'nombre' => 'Elías Sánchez Rubio']);
DB::table('municipio')->insert([ 'id_municipio'=> '320', 'nombre' => 'Guajira']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Altagracia']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Antímano']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Caricuao']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Catedral']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Coche']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'El Junquito']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'El Paraíso']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'El Recreo']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'El Valle']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'La Candelaria']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'La Pastora']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'La Vega']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Macarao']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'San Agustín']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'San Bernardino']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'San José']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'San Juan']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'San Pedro']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Santa Rosalía']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Santa Teresa']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => 'Sucre']);
DB::table('municipio')->insert([ 'id_municipio'=> '335', 'nombre' => '23 de enero']);


    }
}
